/**
 * Bosla AI Worker — Cloudflare Worker
 *
 * Actions (POST JSON):
 *   action:"city"  -> return a city we don't have (from cache if we've built it before, else Claude)
 *   action:"parse" -> turn a free-text / voice trip description into a structured plan
 *   action:"list"  -> names of every city we've cached (peek at what's been built)
 *   action:"dump"  -> full data for every cached city (used to bake them permanently into the app)
 *
 * The Anthropic API key lives ONLY here, as an encrypted secret (env.ANTHROPIC_API_KEY).
 * Built cities are remembered in a KV namespace bound as env.CITIES — so each place is
 * generated by Claude at most ONCE, ever; after that it's served free & instant from cache.
 * If no KV is bound, it still works, just without the memory.
 *
 * SETUP: see ai/SETUP.md.
 */

const ALLOWED_ORIGINS = [
  "https://aalfadhala10.github.io",
  "http://localhost",
  "http://127.0.0.1",
];

const TAGS  = ["Culture", "Food", "Nature", "Adventure", "Shopping", "Relax"];
const CONDS = ["veryhot", "hotdry", "hothumid", "warm", "mild", "tropical", "alpine"];

function corsHeaders(origin) {
  const ok = ALLOWED_ORIGINS.some((o) => origin && origin.startsWith(o));
  return {
    "Access-Control-Allow-Origin": ok ? origin : ALLOWED_ORIGINS[0],
    "Access-Control-Allow-Methods": "POST, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type",
  };
}
function reply(obj, status, origin) {
  return new Response(JSON.stringify(obj), {
    status,
    headers: { "Content-Type": "application/json", ...corsHeaders(origin) },
  });
}
function cityKey(name) {
  return String(name || "").toLowerCase().replace(/[^a-z0-9]/g, "");
}

export default {
  async fetch(request, env) {
    const origin = request.headers.get("Origin") || "";
    if (request.method === "OPTIONS") return new Response(null, { headers: corsHeaders(origin) });
    if (request.method !== "POST") return reply({ error: "POST only" }, 405, origin);

    let body;
    try { body = await request.json(); } catch { return reply({ error: "bad json" }, 400, origin); }

    try {
      if (body.action === "city") {
        if (!env.ANTHROPIC_API_KEY) return reply({ error: "server not configured" }, 500, origin);
        const name = String(body.name || "").slice(0, 60).trim();
        if (name.length < 2) return reply({ error: "name too short" }, 400, origin);
        const out = await getOrBuildCity(name, env);
        return reply({ city: out.city, cached: out.cached }, 200, origin);
      }
      if (body.action === "parse") {
        if (!env.ANTHROPIC_API_KEY) return reply({ error: "server not configured" }, 500, origin);
        const text = String(body.text || "").slice(0, 1200).trim();
        if (!text) return reply({ error: "empty text" }, 400, origin);
        return reply({ parsed: await parseTrip(text, env.ANTHROPIC_API_KEY) }, 200, origin);
      }
      if (body.action === "chat") {
        if (!env.ANTHROPIC_API_KEY) return reply({ error: "server not configured" }, 500, origin);
        const msgs = Array.isArray(body.messages)
          ? body.messages.filter((m) => m && (m.role === "user" || m.role === "assistant") && typeof m.content === "string")
              .map((m) => ({ role: m.role, content: String(m.content).slice(0, 1000) }))
              .slice(-20)
          : [];
        if (!msgs.length) return reply({ error: "no messages" }, 400, origin);
        return reply({ chat: await chatTurn(msgs, env.ANTHROPIC_API_KEY) }, 200, origin);
      }
      if (body.action === "suggest") {
        if (!env.ANTHROPIC_API_KEY) return reply({ error: "server not configured" }, 500, origin);
        const text = String(body.text || "").slice(0, 1200).trim();
        if (!text) return reply({ error: "empty text" }, 400, origin);
        return reply({ suggest: await suggestTrip(text, env.ANTHROPIC_API_KEY) }, 200, origin);
      }
      if (body.action === "list")  return reply({ cities: await listNames(env) }, 200, origin);
      if (body.action === "dump")  return reply({ cities: await dumpAll(env) }, 200, origin);
      return reply({ error: "unknown action" }, 400, origin);
    } catch (e) {
      return reply({ error: String(e && e.message ? e.message : e) }, 500, origin);
    }
  },
};

// --- city cache (KV) ------------------------------------------------------------
async function getOrBuildCity(name, env) {
  const kv = env.CITIES; // KV namespace binding (optional)
  const k = cityKey(name);
  if (kv && k) {
    const hit = await kv.get(k, "json");
    if (hit) return { city: hit, cached: true };
  }
  const city = await generateCity(name, env.ANTHROPIC_API_KEY);
  if (kv && city && city.valid) {
    await kv.put(k, JSON.stringify(city));                 // remember under the searched name
    const ck = cityKey(city.city);                          // ...and its canonical name
    if (ck && ck !== k) await kv.put(ck, JSON.stringify(city));
  }
  return { city, cached: false };
}
async function listNames(env) {
  if (!env.CITIES) return [];
  const names = []; let cursor, done = false;
  while (!done) {
    const res = await env.CITIES.list(cursor ? { cursor } : {});
    res.keys.forEach((x) => names.push(x.name));
    done = res.list_complete; cursor = res.cursor;
  }
  return names;
}
async function dumpAll(env) {
  const names = await listNames(env);
  const out = {};
  for (const n of names) { const v = await env.CITIES.get(n, "json"); if (v) out[n] = v; }
  return out;
}

// --- Claude call with guaranteed-JSON output (structured outputs) ---------------
async function claude(apiKey, model, system, user, schema, maxTokens) {
  const r = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "x-api-key": apiKey,
      "anthropic-version": "2023-06-01",
      "content-type": "application/json",
    },
    body: JSON.stringify({
      model,
      max_tokens: maxTokens,
      system,
      messages: Array.isArray(user) ? user : [{ role: "user", content: user }],
      output_config: { format: { type: "json_schema", schema } },
    }),
  });
  const data = await r.json();
  if (data.type === "error") throw new Error(data.error && data.error.message || "api error");
  const txt = (data.content || []).filter((b) => b.type === "text").map((b) => b.text).join("");
  return JSON.parse(txt);
}

// --- Generate a missing city (Sonnet — accuracy matters, and it's cached after) --
const CITY_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: ["valid","city","country","flag","region","blurbEn","blurbAr","blurbEs",
    "summerCond","summerTemp","costBudget","costMid","costLux","curSymbol","curRate",
    "lat","lng","poi","food","hotelsBudget","hotelsMid","hotelsLux"],
  properties: {
    valid: { type: "boolean" },
    city: { type: "string" }, country: { type: "string" }, flag: { type: "string" },
    region: { type: "string", enum: ["eu","asia","me","africa","islands","americas","oceania"] },
    blurbEn: { type: "string" }, blurbAr: { type: "string" }, blurbEs: { type: "string" },
    summerCond: { type: "string", enum: CONDS }, summerTemp: { type: "integer" },
    costBudget: { type: "integer" }, costMid: { type: "integer" }, costLux: { type: "integer" },
    curSymbol: { type: "string" }, curRate: { type: "number" },
    lat: { type: "number" }, lng: { type: "number" },
    poi: { type: "array", items: { type: "object", additionalProperties: false,
      required: ["n","a","t","lat","lng"], properties: {
        n: { type: "string", description: "attraction name in English" },
        a: { type: "string", description: "short area/neighbourhood label in English, e.g. 'Old Town', 'Marina' — NOT a translation of the name, never Arabic" },
        t: { type: "array", items: { type: "string", enum: TAGS } },
        lat: { type: "number" }, lng: { type: "number" } } } },
    food: { type: "array", items: { type: "object", additionalProperties: false,
      required: ["n","a"], properties: {
        n: { type: "string", description: "restaurant name in English" },
        a: { type: "string", description: "short cuisine/area label in English, e.g. 'Seafood · Marina' — never Arabic" } } } },
    hotelsBudget: { type: "array", items: { type: "string" } },
    hotelsMid: { type: "array", items: { type: "string" } },
    hotelsLux: { type: "array", items: { type: "string" } },
  },
};

function generateCity(name, apiKey) {
  const system =
    "You produce accurate travel data for a real city or town for a trip-planning app. " +
    "Use only REAL, well-known points of interest and their true latitude/longitude. " +
    "If the requested place is not a real, travelable destination, return valid=false and leave other fields blank/zero.\n" +
    "Rules: costs are USD per person per day (Budget/Mid/Luxury). curSymbol/curRate are the local " +
    "currency symbol and its rate to 1 USD (e.g. EUR curRate 0.92). summerTemp is the typical August high in Celsius. " +
    "Give 7 POIs (each with 1-2 tags from Culture/Food/Nature/Shopping/Relax and real coordinates) and 5 food spots " +
    "(favor halal-friendly or clearly vegetarian options where they genuinely exist, matching real restaurants). " +
    "Give 4-5 real hotel names per tier. All POI names, food names, hotel names, and their area/label fields must be in ENGLISH " +
    "(the ONLY Arabic/Spanish fields are blurbAr/blurbEs). blurbEn/Ar/Es are one short vivid sentence each (Arabic and Spanish translations). " +
    "flag is the country's flag emoji. Pick region from the allowed list.";
  return claude(apiKey, "claude-sonnet-5", system, "Generate travel data for: " + name, CITY_SCHEMA, 2200);
}

// --- Parse a free-text / voice trip description (Haiku — cheap, runs per plan) ---
const PARSE_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: ["cities", "days", "vibes", "budget", "roadtrip"],
  properties: {
    cities: { type: "array", items: { type: "string" } },
    days: { type: "integer" },
    vibes: { type: "array", items: { type: "string", enum: TAGS } },
    budget: { type: "string", enum: ["Budget", "Mid-range", "Luxury"] },
    roadtrip: { type: "boolean" },
  },
};

// --- Conversational trip assistant (Haiku) — chats, then hands off a trip to build --------------
const CHAT_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: ["reply", "ready", "cities", "days", "vibes", "budget", "roadtrip", "chips"],
  properties: {
    reply: { type: "string" },      // the message to show the user
    ready: { type: "boolean" },     // true once there's enough to build a trip
    cities: { type: "array", items: { type: "string" } }, // best base city per stop, in order (when ready)
    days: { type: "integer" },
    vibes: { type: "array", items: { type: "string", enum: TAGS } },
    budget: { type: "string", enum: ["Budget", "Mid-range", "Luxury"] },
    roadtrip: { type: "boolean" },
    chips: { type: "array", items: { type: "string" } }, // 0-4 short tappable quick replies for the user
  },
};

function chatTurn(messages, apiKey) {
  const system =
    "You are Bosla (بوصلة), a warm, concise travel assistant inside a trip-planning app. " +
    "Your job: in AT MOST 2-3 short friendly turns, learn (a) roughly WHERE they want to go — a place, or " +
    "a vibe you turn into a concrete suggestion — and (b) HOW MANY days. Ask ONE question at a time, keep every " +
    "reply to 1-3 sentences, no lists. If they're unsure where, suggest 2-3 fitting destinations (keep them " +
    "geographically sensible and make sure each city is in its CORRECT country) and let them pick. " +
    "NEVER assume the user's country, nationality, home city, or where they live — do NOT say 'here', 'at home', " +
    "'عندنا', 'near you', or imply you know their location. Only apply passport/visa constraints if the user " +
    "EXPLICITLY states their nationality; otherwise don't mention visas. " +
    "Once you have at least one concrete destination (named or agreed) AND a rough number of days, set ready=true, " +
    "and fill cities (the best single base CITY per stop, in visit order, common English names), days, vibes (0-3), " +
    "budget (default Mid-range), and roadtrip (true only if the stops are drivable). When ready, make your reply a " +
    "short confirmation like 'Perfect — building your Kyoto trip now.' Until ready, set ready=false and cities=[]. " +
    "ALWAYS fill `chips` with 2-4 SHORT tappable quick-replies (under ~20 chars each, in the user's language) that " +
    "answer your current question effortlessly — e.g. day counts ('5 days','7 days','10 days'), the destinations you " +
    "just suggested, or budgets. Leave chips empty only when ready=true. " +
    "Stay on travel. Never state hard specifics (exact prices, precise visa rules) as fact — speak generally and " +
    "suggest they verify. Reply in the user's language. When they write in Arabic, reply in warm, natural " +
    "GULF / KHALEEJI Arabic (Saudi style) — casual and friendly (e.g. 'وش رايك', 'تبي', 'خلّينا', 'عندك') — " +
    "NOT Egyptian dialect and NOT stiff formal standard Arabic.";
  return claude(apiKey, "claude-haiku-4-5", system, messages, CHAT_SCHEMA, 700);
}

// --- Suggest destinations from a vibe/need when the user names no place (Haiku) ------------------
const SUGGEST_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: ["suggestions", "days", "vibes", "budget", "roadtrip"],
  properties: {
    suggestions: { type: "array", items: { type: "object", additionalProperties: false,
      required: ["place", "country", "flag", "why"], properties: {
        place: { type: "string" }, country: { type: "string" },
        flag: { type: "string" }, why: { type: "string" } } } },
    days: { type: "integer" },
    vibes: { type: "array", items: { type: "string", enum: TAGS } },
    budget: { type: "string", enum: ["Budget", "Mid-range", "Luxury"] },
    roadtrip: { type: "boolean" },
  },
};

function suggestTrip(text, apiKey) {
  const system =
    "The user describes what they want from a trip but usually does NOT name a destination. " +
    "Suggest 2-3 real destinations that genuinely fit. For each: place = the single best CITY to plan " +
    "for that activity (e.g. safari → Nairobi or Arusha; skiing → Chamonix), country = its country, " +
    "flag = the country's flag emoji, why = one short friendly sentence on why it fits. " +
    "Make the suggestions genuinely distinct and relevant, and make sure each city is in its CORRECT country. " +
    "Do NOT assume the user's country or where they live; don't say 'here' or 'near you'. " +
    "Honor every constraint the user gives: if they mention a nationality/passport, only pick countries that are " +
    "visa-free or visa-on-arrival for it (e.g. a Philippine passport: yes Thailand/Indonesia/Malaysia, no Australia/NZ); " +
    "if they want to drive / self-drive / a road trip, set roadtrip true and pick places that suit driving. " +
    "Write `why` in the SAME language the user wrote in; if they wrote in Arabic, use warm Gulf/Khaleeji (Saudi) " +
    "dialect, not Egyptian or formal standard Arabic. " +
    "days: total days if stated, else 0. vibes: 0-3 from the allowed tags. budget: default Mid-range.";
  return claude(apiKey, "claude-haiku-4-5", system, text, SUGGEST_SCHEMA, 700);
}

function parseTrip(text, apiKey) {
  const system =
    "Extract a structured trip from the user's description (any language, typos allowed). " +
    "cities: ONLY destinations the user EXPLICITLY names, in the order visited, corrected to common English names. " +
    "If the user names no specific city or country and only describes a vibe/need, return an EMPTY cities array — " +
    "do NOT invent destinations (a separate step will suggest places to them). " +
    "days: total days — if the text lists nights per stop, SUM them; 0 if not stated. vibes: 0-3 from the allowed tags. " +
    "budget: Budget, Mid-range, or Luxury (default Mid-range). " +
    "roadtrip: true ONLY if the named cities can realistically be driven between (same country or landmass, not across an ocean).";
  return claude(apiKey, "claude-haiku-4-5", system, text, PARSE_SCHEMA, 500);
}
