/**
 * Bosla AI Worker — Cloudflare Worker
 *
 * Actions (POST JSON):
 *   action:"city"  -> return a city we don't have (from cache if we've built it before, else Claude)
 *   action:"parse" -> turn a free-text / voice trip description into a structured plan
 *   action:"list"  -> names of every city we've cached (peek at what's been built)
 *   action:"dump"  -> full data for every cached city (used to bake them permanently into the app)
 *
 * The Anthropic API key lives ONLY here, as an encrypted secret (env.ANTHROPIC_API_KEY).
 * Built cities are remembered in a KV namespace bound as env.CITIES — so each place is
 * generated by Claude at most ONCE, ever; after that it's served free & instant from cache.
 * If no KV is bound, it still works, just without the memory.
 *
 * SETUP: see ai/SETUP.md.
 */

const ALLOWED_ORIGINS = [
  "https://aalfadhala10.github.io",
  "http://localhost",
  "http://127.0.0.1",
];

const TAGS  = ["Culture", "Food", "Nature", "Adventure", "Shopping", "Relax"];
const CONDS = ["veryhot", "hotdry", "hothumid", "warm", "mild", "tropical", "alpine"];

function corsHeaders(origin) {
  const ok = ALLOWED_ORIGINS.some((o) => origin && origin.startsWith(o));
  return {
    "Access-Control-Allow-Origin": ok ? origin : ALLOWED_ORIGINS[0],
    "Access-Control-Allow-Methods": "POST, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type",
  };
}
function reply(obj, status, origin) {
  return new Response(JSON.stringify(obj), {
    status,
    headers: { "Content-Type": "application/json", ...corsHeaders(origin) },
  });
}
function cityKey(name) {
  return String(name || "").toLowerCase().replace(/[^a-z0-9]/g, "");
}

export default {
  async fetch(request, env) {
    const origin = request.headers.get("Origin") || "";
    if (request.method === "OPTIONS") return new Response(null, { headers: corsHeaders(origin) });
    if (request.method !== "POST") return reply({ error: "POST only" }, 405, origin);

    let body;
    try { body = await request.json(); } catch { return reply({ error: "bad json" }, 400, origin); }

    try {
      if (body.action === "city") {
        if (!env.ANTHROPIC_API_KEY) return reply({ error: "server not configured" }, 500, origin);
        const name = String(body.name || "").slice(0, 60).trim();
        if (name.length < 2) return reply({ error: "name too short" }, 400, origin);
        const out = await getOrBuildCity(name, env);
        return reply({ city: out.city, cached: out.cached }, 200, origin);
      }
      if (body.action === "parse") {
        if (!env.ANTHROPIC_API_KEY) return reply({ error: "server not configured" }, 500, origin);
        const text = String(body.text || "").slice(0, 1200).trim();
        if (!text) return reply({ error: "empty text" }, 400, origin);
        return reply({ parsed: await parseTrip(text, env.ANTHROPIC_API_KEY) }, 200, origin);
      }
      if (body.action === "chat") {
        if (!env.ANTHROPIC_API_KEY) return reply({ error: "server not configured" }, 500, origin);
        const msgs = Array.isArray(body.messages)
          ? body.messages.filter((m) => m && (m.role === "user" || m.role === "assistant") && typeof m.content === "string")
              .map((m) => ({ role: m.role, content: String(m.content).slice(0, 1000) }))
              .slice(-20)
          : [];
        while (msgs.length && msgs[0].role !== "user") msgs.shift();                       // must START on a user turn
        while (msgs.length && msgs[msgs.length - 1].role !== "user") msgs.pop();            // must NOT end on assistant (a trailing "…"/prefill breaks structured outputs)
        if (!msgs.length) return reply({ error: "no messages" }, 400, origin);
        return reply({ chat: await chatTurn(msgs, env.ANTHROPIC_API_KEY) }, 200, origin);
      }
      if (body.action === "suggest") {
        if (!env.ANTHROPIC_API_KEY) return reply({ error: "server not configured" }, 500, origin);
        const text = String(body.text || "").slice(0, 1200).trim();
        if (!text) return reply({ error: "empty text" }, 400, origin);
        return reply({ suggest: await suggestTrip(text, env.ANTHROPIC_API_KEY) }, 200, origin);
      }
      if (body.action === "list")  return reply({ cities: await listNames(env) }, 200, origin);
      if (body.action === "dump")  return reply({ cities: await dumpAll(env) }, 200, origin);
      return reply({ error: "unknown action" }, 400, origin);
    } catch (e) {
      return reply({ error: String(e && e.message ? e.message : e) }, 500, origin);
    }
  },
};

// --- city cache (KV) ------------------------------------------------------------
async function getOrBuildCity(name, env) {
  const kv = env.CITIES; // KV namespace binding (optional)
  const k = cityKey(name);
  if (kv && k) {
    const hit = await kv.get(k, "json");
    if (hit) return { city: hit, cached: true };
  }
  const city = await generateCity(name, env.ANTHROPIC_API_KEY);
  if (kv && city && city.valid) {
    await kv.put(k, JSON.stringify(city));                 // remember under the searched name
    const ck = cityKey(city.city);                          // ...and its canonical name
    if (ck && ck !== k) await kv.put(ck, JSON.stringify(city));
  }
  return { city, cached: false };
}
async function listNames(env) {
  if (!env.CITIES) return [];
  const names = []; let cursor, done = false;
  while (!done) {
    const res = await env.CITIES.list(cursor ? { cursor } : {});
    res.keys.forEach((x) => names.push(x.name));
    done = res.list_complete; cursor = res.cursor;
  }
  return names;
}
async function dumpAll(env) {
  const names = await listNames(env);
  const out = {};
  for (const n of names) { const v = await env.CITIES.get(n, "json"); if (v) out[n] = v; }
  return out;
}

// --- Claude call with guaranteed-JSON output (structured outputs) ---------------
// Retries transient upstream errors (429/500/502/503/529 — the API occasionally
// answers "error code: 502" as plain text), and surfaces a clear error otherwise.
async function claude(apiKey, model, system, user, schema, maxTokens) {
  const body = JSON.stringify({
    model,
    max_tokens: maxTokens,
    // The system prompt is the same every turn and every user, so we let Anthropic cache it:
    // a cache read costs ~10% of a normal input token. The bot's prompt is ~2k tokens, which is
    // most of each request — caching it roughly halves the cost of a whole conversation.
    system: [{ type: "text", text: system, cache_control: { type: "ephemeral" } }],
    messages: Array.isArray(user) ? user : [{ role: "user", content: user }],
    output_config: { format: { type: "json_schema", schema } },
  });
  let lastErr;
  for (let attempt = 0; attempt < 3; attempt++) {
    let r;
    try {
      r = await fetch("https://api.anthropic.com/v1/messages", {
        method: "POST",
        headers: {
          "x-api-key": apiKey,
          "anthropic-version": "2023-06-01",
          "content-type": "application/json",
        },
        body,
      });
    } catch (e) {
      lastErr = new Error("network: " + (e && e.message ? e.message : e));
      await sleep(400 * (attempt + 1));
      continue;
    }
    const raw = await r.text();
    if (!r.ok) {
      lastErr = new Error("anthropic " + r.status + ": " + raw.slice(0, 200));
      if (r.status === 429 || r.status >= 500) { await sleep(500 * (attempt + 1)); continue; } // transient — retry
      throw lastErr; // 4xx (bad request/auth/model) — don't retry
    }
    let data;
    try { data = JSON.parse(raw); }
    catch { throw new Error("non-JSON reply from Claude: " + raw.slice(0, 200)); }
    if (data.type === "error") throw new Error(data.error && data.error.message || "api error");
    const txt = (data.content || []).filter((b) => b.type === "text").map((b) => b.text).join("");
    try { return JSON.parse(txt); }
    catch { throw new Error("Claude did not return valid JSON"); }
  }
  throw lastErr || new Error("api unavailable");
}
function sleep(ms) { return new Promise((res) => setTimeout(res, ms)); }

// --- Generate a missing city (Sonnet — accuracy matters, and it's cached after) --
const CITY_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: ["valid","city","country","flag","region","blurbEn","blurbAr","blurbEs",
    "summerCond","summerTemp","costBudget","costMid","costLux","curSymbol","curRate",
    "lat","lng","poi","food","hotelsBudget","hotelsMid","hotelsLux"],
  properties: {
    valid: { type: "boolean" },
    city: { type: "string" }, country: { type: "string" }, flag: { type: "string" },
    region: { type: "string", enum: ["eu","asia","me","africa","islands","americas","oceania"] },
    blurbEn: { type: "string" }, blurbAr: { type: "string" }, blurbEs: { type: "string" },
    summerCond: { type: "string", enum: CONDS }, summerTemp: { type: "integer" },
    costBudget: { type: "integer" }, costMid: { type: "integer" }, costLux: { type: "integer" },
    curSymbol: { type: "string" }, curRate: { type: "number" },
    lat: { type: "number" }, lng: { type: "number" },
    poi: { type: "array", items: { type: "object", additionalProperties: false,
      required: ["n","a","t","lat","lng"], properties: {
        n: { type: "string", description: "attraction name in English" },
        a: { type: "string", description: "short area/neighbourhood label in English, e.g. 'Old Town', 'Marina' — NOT a translation of the name, never Arabic" },
        t: { type: "array", items: { type: "string", enum: TAGS } },
        lat: { type: "number" }, lng: { type: "number" } } } },
    food: { type: "array", items: { type: "object", additionalProperties: false,
      required: ["n","a"], properties: {
        n: { type: "string", description: "restaurant name in English" },
        a: { type: "string", description: "short cuisine/area label in English, e.g. 'Seafood · Marina' — never Arabic" } } } },
    hotelsBudget: { type: "array", items: { type: "string" } },
    hotelsMid: { type: "array", items: { type: "string" } },
    hotelsLux: { type: "array", items: { type: "string" } },
  },
};

function generateCity(name, apiKey) {
  const system =
    "You produce accurate travel data for a real city or town for a trip-planning app. " +
    "Use only REAL, well-known points of interest and their true latitude/longitude. " +
    "If the requested place is not a real, travelable destination, return valid=false and leave other fields blank/zero.\n" +
    "Rules: costs are USD per person per day (Budget/Mid/Luxury). curSymbol/curRate are the local " +
    "currency symbol and its rate to 1 USD (e.g. EUR curRate 0.92). summerTemp is the typical August high in Celsius. " +
    "Give 7 POIs (each with 1-2 tags from Culture/Food/Nature/Shopping/Relax and real coordinates) and 5 food spots " +
    "(favor halal-friendly or clearly vegetarian options where they genuinely exist, matching real restaurants). " +
    "Give 4-5 real hotel names per tier. All POI names, food names, hotel names, and their area/label fields must be in ENGLISH " +
    "(the ONLY Arabic/Spanish fields are blurbAr/blurbEs). blurbEn/Ar/Es are one short vivid sentence each (Arabic and Spanish translations). " +
    "flag is the country's flag emoji. Pick region from the allowed list.";
  return claude(apiKey, "claude-sonnet-5", system, "Generate travel data for: " + name, CITY_SCHEMA, 2200);
}

// --- Parse a free-text / voice trip description (Haiku — cheap, runs per plan) ---
const PARSE_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: ["cities", "days", "vibes", "budget", "roadtrip"],
  properties: {
    cities: { type: "array", items: { type: "string" } },
    days: { type: "integer" },
    vibes: { type: "array", items: { type: "string", enum: TAGS } },
    budget: { type: "string", enum: ["Budget", "Mid-range", "Luxury"] },
    roadtrip: { type: "boolean" },
  },
};

// --- Conversational trip assistant (Haiku) — chats, then hands off a trip to build --------------
const CHAT_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: ["reply", "ready", "cities", "nights", "extras", "days", "vibes", "budget", "roadtrip", "area", "adults", "kids", "chips"],
  properties: {
    reply: { type: "string" },      // the message to show the user
    ready: { type: "boolean" },     // true once there's enough to build a trip
    cities: { type: "array", items: { type: "string" } }, // best base city per stop, in order (when ready)
    nights: { type: "array", items: { type: "integer" } }, // nights per city, same order/length as cities ([] when unknown)
    extras: {                                             // small stops to add to a day (a cafe, an ice cream place)
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["day", "name"],
        properties: { day: { type: "integer" }, name: { type: "string" } },
      },
    },
    area: { type: "string" },       // where they want to stay in the first city (e.g. "Patong", "city center"); "" if they don't mind
    adults: { type: "integer" },    // how many adults are travelling (0 = not asked yet / unknown)
    kids: { type: "integer" },      // how many children (0 = none)
    days: { type: "integer" },
    vibes: { type: "array", items: { type: "string", enum: TAGS } },
    budget: { type: "string", enum: ["Budget", "Mid-range", "Luxury"] },
    roadtrip: { type: "boolean" },
    chips: { type: "array", items: { type: "string" } }, // 0-4 short tappable quick replies for the user
  },
};

function chatTurn(messages, apiKey) {
  const system =
    "You are Bosla (بوصلة), a warm, concise travel assistant inside a trip-planning app. " +
    "Your job: in a few short friendly turns, learn (a) roughly WHERE they want to go — a place, or " +
    "a vibe you turn into a concrete suggestion — and (b) HOW MANY days. Ask ONE question at a time, keep every " +
    "reply to 1-3 sentences, no lists. Be a real RECOMMENDER: if they're unsure where, or ask for ideas, suggest " +
    "2-3 fitting destinations (keep them geographically sensible and make sure each city is in its CORRECT country) " +
    "and let them pick. Proactively propose a sensible route order and day split when helpful. " +
    "NEVER assume the user's country, nationality, home city, or where they live — do NOT say 'here', 'at home', " +
    "'عندنا', 'near you', or imply you know their location. Only apply passport/visa constraints if the user " +
    "EXPLICITLY states their nationality; otherwise don't mention visas. " +
    "ROAD TRIPS: if the trip involves driving between stops, a full plan needs the CAR LOGISTICS, so ask about them " +
    "(one short question at a time) BEFORE you finish: are they renting a car? Is it a LOOP (drop the car back where " +
    "they picked it up / fly home from the same airport) or ONE-WAY (drop it in a different city and fly out from " +
    "there)? Which city/airport will they fly home from? Then reflect the answer in `cities`: for a loop, make the " +
    "LAST stop the same city they started from (the return-to-airport leg); for one-way, make the last stop the " +
    "city they fly out of. Set roadtrip=true for these. " +
    "ARRIVAL & DEPARTURE — ALWAYS ACCOUNT FOR THIS. Many towns have no airport, so the traveller lands somewhere " +
    "else and continues by car or train. Before finishing, work out which airport they realistically fly into and " +
    "out of, and SAY IT in your reply — e.g. for Garmisch-Partenkirchen: 'You'd fly into Munich, then it's about a " +
    "1.5h drive to Garmisch — do you want a night in Munich first, or drive straight down?'. Reflect the answer in " +
    "`cities`: if they arrive the night before, make the gateway city the FIRST stop; if they drive straight " +
    "through, still mention the arrival drive in your reply. Do the same for the flight home — leave enough time to " +
    "get back to the departure airport, and make that city the LAST stop when they need a night there. Never " +
    "produce a plan that silently assumes they materialise in a town with no airport. " +
    "WHO'S TRAVELLING: also ask, in ONE short question, how many people are going and whether any children are " +
    "coming (e.g. 'How many of you are travelling — and any kids?'). Put the answer in `adults` and `kids` " +
    "(kids=0 when none). Ask it only ONCE, and if they already said (e.g. 'me and my wife', 'family of 4 with 2 " +
    "kids') just fill the numbers without asking. If they never say, leave adults=0 and kids=0 and don't block the " +
    "trip on it. Offer chips like 'Just me', '2 adults', 'Family with kids'. " +
    "WHERE THEY'LL STAY: after the destination is settled, ask ONE short question about which area they want to " +
    "stay in — e.g. 'Where do you want to be based? Near the beach, city center, near the airport, or somewhere " +
    "specific in mind?' — and offer chips for the areas that actually make sense in THAT city (for Phuket: 'Patong', " +
    "'Kata Beach', 'Old Town'; for Dubai: 'Marina', 'Downtown'). Put their answer in `area` (a real neighbourhood " +
    "name when they name one, otherwise a short phrase like 'city center' / 'near the airport'). Ask it only ONCE; " +
    "if they already said where they want to stay, or they say it doesn't matter / you choose, set area='' and move " +
    "on. Never block the trip on this question. " +
    "Once you have at least one concrete destination (named or agreed) AND a rough number of days — and, for a road " +
    "trip, the car return/airport plan — set ready=true, and fill cities (the best single MAIN city per stop, in " +
    "visit order, common English names), days, vibes (0-3), budget (default Mid-range), roadtrip, area, adults and " +
    "kids. When ready, make your reply a short confirmation like 'Perfect — building your Alps loop from Munich " +
    "now.' Until ready, set ready=false and cities=[]. Set area='' and adults/kids=0 whenever you don't know yet, and " +
    "nights=[] and extras=[] whenever you have nothing to put in them. " +
    "ALWAYS fill `chips` with 2-4 SHORT tappable quick-replies (under ~20 chars each, in the user's language) that " +
    "answer your current question effortlessly — e.g. day counts ('5 days','7 days','10 days'), the destinations you " +
    "just suggested, budgets, or for the car question ('Loop, same airport','One-way','Renting a car'). Leave chips " +
    "empty only when ready=true. " +
    "WHAT THE APP ITSELF CAN DO — SAY SO WHEN IT'S RELEVANT. Many things people ask you for are already features " +
    "of the finished plan, so never answer 'I can't' and never promise to do it yourself in the chat. Instead say, " +
    "in ONE short sentence, that it's waiting for them on the plan — e.g. 'And once the plan is up you can tap any " +
    "place to see a photo of it.' Mention it when they ask for it, and when you confirm the plan is ready pick the " +
    "ONE feature that best answers what they were after and mention just that (never a list). The plan gives them: " +
    "a photo of any place (hover it on a computer, tap the small photo button on a phone); every place name opens in " +
    "Google Maps, and each city-to-city leg links to the real driving route or a flight search; swap any single " +
    "sight or restaurant for another, or reshuffle a whole day; breakfast, lunch and dinner every day, with a map " +
    "search for more restaurants if they don't want the local picks; set the nights per city freely (8 here, 4 " +
    "there) and delete a city they don't want; change how many adults and kids are travelling; a hotel search they " +
    "steer by area and by type (hotel, apartment, resort, villa, hostel); a budget breakdown with a currency " +
    "converter and a check against their own budget; weather, prayer times and halal notes, useful local phrases, " +
    "handy apps and a packing list; and they can save the trip, share a link, print it as a PDF or add it to their " +
    "calendar, in English, Arabic or Spanish. " +
    "EDITING A TRIP THAT ALREADY EXISTS. The traveller's message may end with a bracketed line like " +
    "'[Current plan - cities: Munich 2n > Garmisch 3n; total days: 5; travellers: 2 adults, 1 kid; staying near: Marina]'. " +
    "They did not type that — it is the trip already on their screen. Whenever it is there you are EDITING, never starting " +
    "over: apply ONLY the change they asked for and carry everything else through untouched. Set ready=true and return the " +
    "COMPLETE updated trip — every city in order, days, nights, area, adults, kids — because anything you leave out is lost. " +
    "Use `nights` to give the exact nights per city (same order and length as `cities`) whenever a split is known or asked " +
    "for, e.g. 8 nights in Phuket and 4 in Bangkok; leave it empty when you don't know. If they ask to ADD a small stop — a " +
    "coffee shop, an ice cream place, a viewpoint, a market — put it in `extras` as {day, name} using the day number from " +
    "their plan, name a real place in the right city, and leave cities/days/nights exactly as they were. If they want to " +
    "change one specific sight or restaurant, do NOT rebuild the trip: tell them to tap the small swap arrows next to that " +
    "place on the plan. If they say the trip is good as it is, reply warmly and briefly and set ready=false. " +
    "Stay on travel. Never state hard specifics (exact prices, precise visa rules) as fact — speak generally and " +
    "suggest they verify. Reply in the user's language. " +
    "WRITING QUALITY IS CRITICAL. When the user writes in Arabic, reply ONLY in clean, natural, grammatically-correct " +
    "GULF / KHALEEJI Arabic (Saudi style) — warm and casual (e.g. 'وش رايك', 'تبي', 'خلّينا', 'عندك'), NOT Egyptian and " +
    "NOT stiff formal standard Arabic. Write COMPLETE, COHERENT sentences. Do NOT mix English words, transliterations, " +
    "or internal/technical terms (like 'base', 'loop', 'vibe', 'road trip') into the Arabic text — only real place " +
    "names keep their normal spelling. Never output broken, half-translated, or garbled phrases; before you answer, " +
    "make sure every Arabic sentence reads naturally to a Gulf speaker. Both `reply` and every item in `chips` must " +
    "follow this same clean-Arabic rule. Re-read your Arabic before sending it: correct spelling, correct " +
    "grammar, correct word order, no missing or duplicated words, no dropped letters, and never a sentence " +
    "that stops halfway. A single Arabic mistake is worse than a slower answer.";
  // Arabic is the one language a small model keeps getting wrong (broken grammar, half-translated
  // words). Real users noticed, so Arabic conversations go to the bigger model; EN/ES stay on Haiku.
  return claude(apiKey, writesArabic(messages) ? "claude-sonnet-5" : "claude-haiku-4-5", system, messages, CHAT_SCHEMA, 700);
}

// True when the traveller is actually writing Arabic (not just one stray word).
function writesArabic(messages) {
  const said = (Array.isArray(messages) ? messages : [])
    .filter((m) => m && m.role === "user")
    .map((m) => String(m.content || ""))
    .join(" ");
  const arabic = (said.match(/[\u0600-\u06FF]/g) || []).length;
  const letters = (said.match(/[\u0600-\u06FFA-Za-z]/g) || []).length;
  return letters > 0 && arabic / letters > 0.3;
}

// --- Suggest destinations from a vibe/need when the user names no place (Haiku) ------------------
const SUGGEST_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: ["suggestions", "days", "vibes", "budget", "roadtrip"],
  properties: {
    suggestions: { type: "array", items: { type: "object", additionalProperties: false,
      required: ["place", "country", "flag", "why"], properties: {
        place: { type: "string" }, country: { type: "string" },
        flag: { type: "string" }, why: { type: "string" } } } },
    days: { type: "integer" },
    vibes: { type: "array", items: { type: "string", enum: TAGS } },
    budget: { type: "string", enum: ["Budget", "Mid-range", "Luxury"] },
    roadtrip: { type: "boolean" },
  },
};

function suggestTrip(text, apiKey) {
  const system =
    "The user describes what they want from a trip but usually does NOT name a destination. " +
    "Suggest 2-3 real destinations that genuinely fit. For each: place = the single best CITY to plan " +
    "for that activity (e.g. safari → Nairobi or Arusha; skiing → Chamonix), country = its country, " +
    "flag = the country's flag emoji, why = one short friendly sentence on why it fits. " +
    "Make the suggestions genuinely distinct and relevant, and make sure each city is in its CORRECT country. " +
    "Do NOT assume the user's country or where they live; don't say 'here' or 'near you'. " +
    "Honor every constraint the user gives: if they mention a nationality/passport, only pick countries that are " +
    "visa-free or visa-on-arrival for it (e.g. a Philippine passport: yes Thailand/Indonesia/Malaysia, no Australia/NZ); " +
    "if they want to drive / self-drive / a road trip, set roadtrip true and pick places that suit driving. " +
    "Write `why` in the SAME language the user wrote in; if they wrote in Arabic, use warm Gulf/Khaleeji (Saudi) " +
    "dialect, not Egyptian or formal standard Arabic. " +
    "days: total days if stated, else 0. vibes: 0-3 from the allowed tags. budget: default Mid-range.";
  return claude(apiKey, "claude-haiku-4-5", system, text, SUGGEST_SCHEMA, 700);
}

function parseTrip(text, apiKey) {
  const system =
    "Extract a structured trip from the user's description (any language, typos allowed). " +
    "cities: ONLY destinations the user EXPLICITLY names, in the order visited, corrected to common English names. " +
    "If the user names no specific city or country and only describes a vibe/need, return an EMPTY cities array — " +
    "do NOT invent destinations (a separate step will suggest places to them). " +
    "days: total days — if the text lists nights per stop, SUM them; 0 if not stated. vibes: 0-3 from the allowed tags. " +
    "budget: Budget, Mid-range, or Luxury (default Mid-range). " +
    "roadtrip: true ONLY if the named cities can realistically be driven between (same country or landmass, not across an ocean).";
  return claude(apiKey, "claude-haiku-4-5", system, text, PARSE_SCHEMA, 500);
}
