/**
 * Bosla AI Worker — Cloudflare Worker
 *
 * Actions (POST JSON):
 *   action:"city"  -> return a city we don't have (from cache if we've built it before, else Claude)
 *   action:"parse" -> turn a free-text / voice trip description into a structured plan
 *   action:"list"  -> names of every city we've cached (peek at what's been built)
 *   action:"dump"  -> full data for every cached city (used to bake them permanently into the app)
 *
 * The Anthropic API key lives ONLY here, as an encrypted secret (env.ANTHROPIC_API_KEY).
 * Built cities are remembered in a KV namespace bound as env.CITIES — so each place is
 * generated by Claude at most ONCE, ever; after that it's served free & instant from cache.
 * If no KV is bound, it still works, just without the memory.
 *
 * SETUP: see ai/SETUP.md.
 */

// Where the app is allowed to be served from. Add a line here BEFORE moving the app to a new
// domain (a Cloudflare Pages address, a custom domain) or it will be turned away from its own
// Worker and every AI feature will go quiet at once.
const ALLOWED_ORIGINS = [
  "https://aalfadhala10.github.io",
  "http://localhost",
  "http://127.0.0.1",
];
function originOk(origin) {
  return ALLOWED_ORIGINS.some((o) => origin && origin.startsWith(o));
}

const TAGS  = ["Culture", "Food", "Nature", "Adventure", "Shopping", "Relax"];
const CONDS = ["veryhot", "hotdry", "hothumid", "warm", "mild", "tropical", "alpine"];

function corsHeaders(origin) {
  const ok = originOk(origin);
  return {
    "Access-Control-Allow-Origin": ok ? origin : ALLOWED_ORIGINS[0],
    "Access-Control-Allow-Methods": "POST, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type",
  };
}
function reply(obj, status, origin) {
  return new Response(JSON.stringify(obj), {
    status,
    headers: { "Content-Type": "application/json", ...corsHeaders(origin) },
  });
}
function cityKey(name) {
  return String(name || "").toLowerCase().replace(/[^a-z0-9]/g, "");
}

// --- keeping the bill yours ------------------------------------------------------
// This worker is a public URL and every answer it gives costs real money — Anthropic for the
// writing, Google for the place lookups. The CORS check above stops nothing: a browser obeys it,
// `curl` doesn't, and the URL is sitting in the page source of the app.
//
// Two counters, both kept in the KV we already have. One is per visitor per minute, which stops a
// single person hammering it. The other is the whole day's spend across everybody, which is the
// backstop for the case the first one can't see — a thousand different addresses at once.
//
// Both count only when money is ACTUALLY spent. A city served from cache costs nothing and is not
// counted, or a popular destination would eat the day's budget on free answers.
// 40, not 25: a family on one home wifi shares a single public address, so five people planning
// at the same time look like one very busy visitor. An actual abuser sends thousands, not dozens —
// the gap between a busy household and an attack is wide enough that this costs nothing to allow.
const RL_PER_MIN     = 40;    // requests a minute from one address
const DAY_LLM_CAP    = 600;   // Claude calls a day, everyone together
const DAY_PLACES_CAP = 2000;  // Google place lookups a day, everyone together

function today() { return new Date().toISOString().slice(0, 10); }

async function peek(kv, key) {
  if (!kv) return 0;
  try { return parseInt(await kv.get(key), 10) || 0; } catch (e) { return 0; }
}
// Read, add, write. Two requests landing in the same millisecond can both read the same number and
// one increment is lost — which is fine here. This is a safety valve, not an invoice: it only has
// to be roughly right, and erring low means a real traveller is never turned away by a rounding
// error. If it ever needs to be exact, that's Durable Objects, and it isn't worth it yet.
async function bump(kv, key, ttl, by) {
  if (!kv) return 0;
  const n = (await peek(kv, key)) + (by || 1);
  try { await kv.put(key, String(n), { expirationTtl: ttl }); } catch (e) {}
  return n;
}
async function overBudget(env, kind, cap) {
  return (await peek(env.CITIES, "spend:" + kind + ":" + today())) >= cap;
}
function spend(env, kind, n) {
  return bump(env.CITIES, "spend:" + kind + ":" + today(), 172800, n || 1);
}
// A minute-stamped key, so yesterday's counters expire themselves and nothing has to be cleaned up.
async function tooFast(env, request) {
  const ip = request.headers.get("CF-Connecting-IP") || "anon";
  const key = "rl:" + ip + ":" + Math.floor(Date.now() / 60000);
  return (await bump(env.CITIES, key, 120)) > RL_PER_MIN;
}

export default {
  async fetch(request, env) {
    const origin = request.headers.get("Origin") || "";
    if (request.method === "OPTIONS") return new Response(null, { headers: corsHeaders(origin) });
    if (request.method !== "POST") return reply({ error: "POST only" }, 405, origin);

    // The allow-list above only ever set a CORS header, and a CORS header is an instruction to a
    // BROWSER about whether it may read an answer that has already been fetched and already been
    // paid for. It stops nothing. Somebody who copies index.html onto their own site — or skips
    // the browser entirely — was spending this account's Anthropic and Google budget, and the
    // first sign of it would have been the bill.
    //
    // Turning an unknown caller away here costs nothing and happens before any of that. It is not
    // airtight: an Origin header is trivially forged outside a browser, so this stops the copy
    // that is re-hosted, not a determined one. The per-minute and per-day caps below are what
    // actually bound the damage, and they are the part to keep tight.
    if (!originOk(origin)) return reply({ error: "not allowed from here" }, 403, origin);

    let body;
    try { body = await request.json(); } catch { return reply({ error: "bad json" }, 400, origin); }

    // One person, too many knocks. 429 is the status that means "not wrong, just slow down" —
    // `retry` tells the app how long to wait so it can say something sensible instead of failing.
    if (await tooFast(env, request)) return reply({ error: "too many requests", retry: 60 }, 429, origin);

    // Everything below that talks to Claude shares one daily allowance, and everything that talks
    // to Google shares another. Checked BEFORE the work, so the call that would break the budget
    // never happens rather than being noticed afterwards.
    const LLM = { city: 1, food: 1, names: 1, chat: 1, parse: 1, suggest: 1, gateway: 1 };
    if (LLM[body.action] && await overBudget(env, "llm", DAY_LLM_CAP))
      return reply({ error: "daily limit reached", retry: 3600 }, 429, origin);
    if (body.action === "places" && await overBudget(env, "places", DAY_PLACES_CAP))
      return reply({ closed: [], rated: {} }, 200, origin);   // silent: the app is fine without it

    try {
      if (body.action === "city") {
        if (!env.ANTHROPIC_API_KEY) return reply({ error: "server not configured" }, 500, origin);
        const name = String(body.name || "").slice(0, 60).trim();
        if (name.length < 2) return reply({ error: "name too short" }, 400, origin);
        const out = await getOrBuildCity(name, env);
        return reply({ city: out.city, cached: out.cached }, 200, origin);
      }
      if (body.action === "parse") {
        if (!env.ANTHROPIC_API_KEY) return reply({ error: "server not configured" }, 500, origin);
        const text = String(body.text || "").slice(0, 1200).trim();
        if (!text) return reply({ error: "empty text" }, 400, origin);
        await spend(env, "llm");
        return reply({ parsed: await parseTrip(text, env.ANTHROPIC_API_KEY) }, 200, origin);
      }
      if (body.action === "chat") {
        if (!env.ANTHROPIC_API_KEY) return reply({ error: "server not configured" }, 500, origin);
        const msgs = Array.isArray(body.messages)
          ? body.messages.filter((m) => m && (m.role === "user" || m.role === "assistant") && typeof m.content === "string")
              .map((m) => ({ role: m.role, content: String(m.content).slice(0, 1000) }))
              .slice(-20)
          : [];
        while (msgs.length && msgs[0].role !== "user") msgs.shift();                       // must START on a user turn
        while (msgs.length && msgs[msgs.length - 1].role !== "user") msgs.pop();            // must NOT end on assistant (a trailing "…"/prefill breaks structured outputs)
        if (!msgs.length) return reply({ error: "no messages" }, 400, origin);
        await spend(env, "llm");
        return reply({ chat: await chatTurn(msgs, env.ANTHROPIC_API_KEY) }, 200, origin);
      }
      if (body.action === "suggest") {
        if (!env.ANTHROPIC_API_KEY) return reply({ error: "server not configured" }, 500, origin);
        const text = String(body.text || "").slice(0, 1200).trim();
        if (!text) return reply({ error: "empty text" }, 400, origin);
        await spend(env, "llm");
        return reply({ suggest: await suggestTrip(text, env.ANTHROPIC_API_KEY) }, 200, origin);
      }
      if (body.action === "food") {
        if (!env.ANTHROPIC_API_KEY) return reply({ error: "server not configured" }, 500, origin);
        const name = String(body.name || "").slice(0, 60).trim();
        if (name.length < 2) return reply({ error: "name too short" }, 400, origin);
        const out = await getOrBuildFood(name, String(body.country || "").slice(0, 60).trim(), env);
        return reply({ food: out.food, cached: out.cached }, 200, origin);
      }
      if (body.action === "names") {
        if (!env.ANTHROPIC_API_KEY) return reply({ error: "server not configured" }, 500, origin);
        const lang = body.lang === "ar" ? "ar" : (body.lang === "es" ? "es" : "");
        const name = String(body.name || "").slice(0, 60).trim();
        const items = Array.isArray(body.items)
          ? body.items.map((n) => String(n || "").slice(0, 80).trim()).filter(Boolean).slice(0, 60)
          : [];
        if (!lang || !items.length) return reply({ names: [] }, 200, origin);
        return reply({ names: await getOrBuildNames(name, String(body.country || "").slice(0, 60).trim(), lang, items, env) }, 200, origin);
      }
      if (body.action === "gateway") {
        if (!env.ANTHROPIC_API_KEY) return reply({ error: "server not configured" }, 500, origin);
        const name = String(body.name || "").slice(0, 60).trim();
        if (name.length < 2) return reply({ error: "name too short" }, 400, origin);
        const out = await getOrBuildGateway(name, String(body.country || "").slice(0, 60).trim(), env);
        return reply({ gateway: out.gw, cached: out.cached }, 200, origin);
      }
      if (body.action === "places") {
        const city = String(body.city || "").slice(0, 60).trim();
        const names = Array.isArray(body.names)
          ? body.names.map((n) => String(n || "").slice(0, 80).trim()).filter(Boolean).slice(0, 40)
          : [];
        if (!names.length) return reply({ closed: [], rated: {} }, 200, origin);
        return reply(await placeFacts(names, city, env), 200, origin);
      }
      if (body.action === "cityphoto") return await cityPhoto(body, env, origin);
      if (body.action === "hotelprice") return await hotelPrice(body, env, origin);

      // --- Community: published trips, likes, comments, photos --------------------------------
      // No accounts, in keeping with the app's promise. Publishing is an explicit act; a name is
      // whatever the traveller typed. Everything lives in the same KV, costs no AI budget, and is
      // bounded hard: sizes, counts, and per-address daily caps. Three reports hide a trip with
      // no admin on duty — a beta can't wait for one.
      if (body.action && body.action.indexOf("pub_") === 0) {
        if (!env.CITIES) return reply({ error: "no storage bound" }, 500, origin);
        return await community(body, env, request, origin);
      }
      // These two hand over every city we have ever built. They're yours, not the public's.
      // Set an ADMIN_KEY secret in Cloudflare and they lock; leave it unset and nothing changes.
      if (body.action === "list" || body.action === "dump") {
        if (env.ADMIN_KEY && body.admin !== env.ADMIN_KEY) return reply({ error: "not allowed" }, 403, origin);
        if (body.action === "list") return reply({ cities: await listNames(env) }, 200, origin);
        return reply({ cities: await dumpAll(env) }, 200, origin);
      }
      return reply({ error: "unknown action" }, 400, origin);
    } catch (e) {
      return reply({ error: String(e && e.message ? e.message : e) }, 500, origin);
    }
  },
};

// --- city cache (KV) ------------------------------------------------------------
async function getOrBuildCity(name, env) {
  const kv = env.CITIES; // KV namespace binding (optional)
  const k = cityKey(name);
  if (kv && k) {
    const hit = await kv.get(k, "json");
    if (hit) return { city: hit, cached: true };
  }
  await spend(env, "llm");                                 // counted here: this is the call that costs
  const city = await generateCity(name, env.ANTHROPIC_API_KEY);
  if (kv && city && city.valid) {
    await kv.put(k, JSON.stringify(city));                 // remember under the searched name
    const ck = cityKey(city.city);                          // ...and its canonical name
    if (ck && ck !== k) await kv.put(ck, JSON.stringify(city));
  }
  return { city, cached: false };
}
// A city ships with a handful of local restaurants, which repeat on a long stay and leave
// nobody an option if they don't want the local cuisine. This widens the menu once per city
// and remembers it in KV, so it is generated at most ONCE, ever, then served free and instant.
async function getOrBuildFood(name, country, env) {
  const kv = env.CITIES;
  const k = "food:" + cityKey(name);
  if (kv && k !== "food:") {
    const hit = await kv.get(k, "json");
    if (hit) return { food: hit, cached: true };
  }
  await spend(env, "llm");
  const res = await generateFood(name, country, env.ANTHROPIC_API_KEY);
  const food = (res && res.valid && Array.isArray(res.food)) ? res.food.filter((f) => f && f.n && f.a) : [];
  if (kv && food.length >= 4) await kv.put(k, JSON.stringify(food));
  return { food, cached: false };
}
// --- what a place is called in the reader's language -----------------------------
// An Arabic itinerary listing "Khan el-Khalili Bazaar" in Latin script reads like a half-finished
// translation. These are real names with real local forms (خان الخليلي), not strings to transliterate.
// Built once per city per language and cached in KV, like everything else here.
const NAMES_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: ["items"],
  properties: {
    items: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["en", "tr"],
        properties: {
          en: { type: "string", description: "the English name exactly as it was given" },
          tr: { type: "string", description: "what the place is actually called in the target language" },
        },
      },
    },
  },
};

async function getOrBuildNames(city, country, lang, items, env) {
  const kv = env.CITIES;
  const k = "names:" + lang + ":" + cityKey(city);
  let have = {};
  if (kv && cityKey(city)) {
    const hit = await kv.get(k, "json");
    if (hit) {
      have = hit;
      // everything already known — no call at all
      if (items.every((n) => have[n])) return items.map((n) => ({ en: n, tr: have[n] }));
    }
  }
  const missing = items.filter((n) => !have[n]);
  await spend(env, "llm");
  const res = await generateNames(city, country, lang, missing, env.ANTHROPIC_API_KEY);
  const got = (res && Array.isArray(res.items)) ? res.items : [];
  got.forEach((x) => { if (x && x.en && x.tr) have[x.en] = x.tr; });
  if (kv && Object.keys(have).length) await kv.put(k, JSON.stringify(have));
  return items.filter((n) => have[n]).map((n) => ({ en: n, tr: have[n] }));
}

function generateNames(city, country, lang, items, apiKey) {
  const target = lang === "ar" ? "Arabic" : "Spanish";
  const system =
    "You give the name a real place is ACTUALLY known by in " + target + " — the name a local would " +
    "say and a taxi driver would recognise, not a transliteration of the English.\n" +
    "Return one entry per input, with `en` copied back EXACTLY as given so it can be matched up.\n" +
    "Use the established local name where one exists (Khan el-Khalili Bazaar -> خان الخليلي; " +
    "Egyptian Museum -> المتحف المصري; Prado Museum -> Museo del Prado). Where a place genuinely has " +
    "no name in that language — a restaurant with a foreign brand name, say — keep the original name " +
    "unchanged rather than inventing or transliterating one. " +
    (lang === "ar"
      ? "Arabic must be correct and natural: proper spelling, the definite article where it belongs, " +
        "no half-translated or garbled forms, no Latin letters mixed in. A wrong Arabic name is worse " +
        "than leaving the English. "
      : "") +
    "Keep every name short — it sits on one line of a phone screen.";
  return claude(apiKey, "claude-sonnet-5", system,
    "Places in " + city + (country ? ", " + country : "") + ":\n" + items.join("\n"),
    NAMES_SCHEMA, 1600);
}

// --- how do you actually get there? ----------------------------------------------
// Plenty of real destinations have no airport. Maasai Mara doesn't; nor does Machu Picchu, or half
// the islands people want. A plan that opens with breakfast in the reserve has quietly skipped the
// part where the traveller lands 230km away and still has to cross a country. Asked once per
// destination and cached forever, because this does not change.
//
// Durations are NUMBERS OF MINUTES, not sentences, so one cached answer serves all three languages
// — the app writes "٤٠–٥٠ دقيقة" or "40–50 min" from the same record.
const GATEWAY_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: ["direct", "airport", "code", "city", "km", "options"],
  properties: {
    direct: { type: "boolean", description: "true if travellers on international flights genuinely land at this place itself" },
    airport: { type: "string", description: "the airport they realistically land at, full name" },
    code: { type: "string", description: "its IATA code, e.g. NBO" },
    city: { type: "string", description: "the city that airport serves, in English" },
    km: { type: "integer", description: "road distance from that airport to the destination" },
    options: {
      type: "array",
      description: "the real ways to cover the last leg, best first. Empty when direct is true.",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["mode", "minMin", "maxMin", "usd", "via"],
        properties: {
          mode: { type: "string", enum: ["air", "road", "rail", "boat"] },
          minMin: { type: "integer", description: "typical duration in MINUTES, low end" },
          maxMin: { type: "integer", description: "typical duration in MINUTES, high end" },
          usd: { type: "integer", description: "rough cost per person in USD, one way" },
          via: { type: "string", description: "short English detail, e.g. 'light aircraft to Ol Kiombo airstrip'; empty if none" },
        },
      },
    },
  },
};

async function getOrBuildGateway(name, country, env) {
  const kv = env.CITIES;
  const k = "gw:" + cityKey(name);
  if (kv && k !== "gw:") {
    const hit = await kv.get(k, "json");
    if (hit) return { gw: hit, cached: true };
  }
  await spend(env, "llm");
  const gw = await generateGateway(name, country, env.ANTHROPIC_API_KEY);
  if (kv && gw && gw.code) await kv.put(k, JSON.stringify(gw));
  return { gw, cached: false };
}

function generateGateway(name, country, apiKey) {
  const system =
    "You answer one question about a real destination: how does a traveller flying in from abroad actually GET there?\n" +
    "Set direct=true ONLY when international or significant domestic flights genuinely land at that place itself, and " +
    "give that airport. Set direct=false whenever the traveller must land somewhere else and continue by air, road, " +
    "rail or boat — a game reserve, a mountain town, a small island, anywhere with no usable airport of its own. " +
    "This is the common case and getting it wrong strands people: never assume a place has an airport because it is " +
    "famous.\n" +
    "When direct=false, `airport`/`code`/`city` are the gateway they realistically fly into, `km` is the road distance " +
    "from it, and `options` are the real ways to cover that last leg, best first — usually 2, never more than 3. " +
    "Include the scheduled light-aircraft hop where one genuinely exists (many safari and island destinations are " +
    "reached that way and it is what most visitors do), and the drive. minMin/maxMin are MINUTES. `usd` is a rough " +
    "per-person one-way cost. `via` is a short English detail such as the airstrip name; leave it empty when there " +
    "is nothing useful to add.\n" +
    "When direct=true, give the airport and its code, set km to 0 and options to an empty array.";
  return claude(apiKey, "claude-sonnet-5", system,
    "How do travellers reach: " + name + (country ? ", " + country : ""), GATEWAY_SCHEMA, 900);
}

// --- is this place still open? (Google Places) -----------------------------------
// A curated list goes stale the moment somewhere shuts, and an itinerary that sends someone to a
// permanently-closed restaurant is worse than no itinerary. Google is the only source that knows.
//
// Each place is looked up ONCE and the verdict cached in KV — a city's ~20 places cost ~20 lookups
// ever, then nothing. OPERATIONAL and unknown are cached for 90 days (things close later); a
// permanent closure is cached for a year, because that doesn't un-happen.
// Needs env.GOOGLE_PLACES_KEY. Without it this quietly returns nothing and the app is unchanged.
const PLACE_TTL_OPEN   = 60 * 60 * 24 * 90;
const PLACE_TTL_CLOSED = 60 * 60 * 24 * 365;

// Returns what Google knows about each place: whether it has shut, and how it's rated. Both come
// from the same lookup, so asking for the rating costs nothing extra beyond the field mask.
async function placeFacts(names, city, env) {
  const out = { closed: [], rated: {}, pins: {}, unknown: [] };
  if (!env.GOOGLE_PLACES_KEY) return out;
  const kv = env.CITIES;
  // Sequential on purpose: a plan is ~20 names, almost all cached after the first traveller, and
  // firing 20 parallel calls at Google from one worker earns a rate limit, not a faster answer.
  for (const name of names) {
    const k = "biz:" + cityKey(city) + ":" + cityKey(name);
    let fact = null;
    if (kv) { try { fact = await kv.get(k, "json"); } catch (e) { fact = null; } }
    if (!fact) {
      await spend(env, "places");                           // one lookup, one unit of the day's budget
      fact = await placeLookup(name, city, env.GOOGLE_PLACES_KEY);
      // Nothing on Google under that name is worth knowing: either the spelling in our data is
      // wrong or the place isn't real, and either way a link to it will come back empty. Reported
      // so the names can be corrected instead of quietly shipping a dead link.
      if (!fact) { out.unknown.push(name); continue; }
      if (kv) await kv.put(k, JSON.stringify(fact),
        { expirationTtl: fact.s === "CLOSED_PERMANENTLY" ? PLACE_TTL_CLOSED : PLACE_TTL_OPEN });
      // fall through
    }
    if (fact.s === "CLOSED_PERMANENTLY") out.closed.push(name);
    // Google knows this pin, so hand back the one thing that makes a link certain.
    if (fact.id) out.pins[name] = { id: fact.id, gn: fact.gn || "", lat: fact.lat || 0, lng: fact.lng || 0 };
    // A 5.0 from four people says less than a 4.3 from nine hundred — carry the count too.
    if (fact.r > 0) out.rated[name] = { r: fact.r, n: fact.n || 0 };
  }
  return out;
}

async function placeLookup(name, city, key) {
  try {
    const r = await fetch("https://places.googleapis.com/v1/places:searchText", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "X-Goog-Api-Key": key,
        // places.id is the whole point of paying for this: it is the ONE string that makes a Maps
        // link land on the exact pin instead of running a text search that can come back empty.
        "X-Goog-FieldMask": "places.id,places.displayName,places.formattedAddress,places.location,places.businessStatus,places.rating,places.userRatingCount",
      },
      body: JSON.stringify({ textQuery: name + (city ? ", " + city : ""), maxResultCount: 1 }),
    });
    if (!r.ok) return null;
    const d = await r.json();
    const p = d && Array.isArray(d.places) && d.places[0];
    if (!p) return null;
    // Google found nothing resembling the name — don't call that a closure, we'd delete good places
    // on a spelling difference. Only an explicit verdict counts.
    const found = String((p.displayName && p.displayName.text) || "").toLowerCase();
    const asked = name.toLowerCase();
    if (found && !found.includes(asked.slice(0, 6)) && !asked.includes(found.slice(0, 6))) return null;
    return {
      s: p.businessStatus || "OPERATIONAL", r: p.rating || 0, n: p.userRatingCount || 0,
      id: p.id || "",                                    // the exact pin, for the map link
      gn: (p.displayName && p.displayName.text) || "",   // what Google itself calls it
      lat: (p.location && p.location.latitude) || 0, lng: (p.location && p.location.longitude) || 0,
    };
  } catch (e) {
    return null;
  }
}

async function listNames(env) {
  if (!env.CITIES) return [];
  const names = []; let cursor, done = false;
  while (!done) {
    const res = await env.CITIES.list(cursor ? { cursor } : {});
    res.keys.forEach((x) => names.push(x.name));
    done = res.list_complete; cursor = res.cursor;
  }
  return names;
}
async function dumpAll(env) {
  const names = await listNames(env);
  const out = {};
  for (const n of names) { const v = await env.CITIES.get(n, "json"); if (v) out[n] = v; }
  return out;
}

// --- Claude call with guaranteed-JSON output (structured outputs) ---------------
// Retries transient upstream errors (429/500/502/503/529 — the API occasionally
// answers "error code: 502" as plain text), and surfaces a clear error otherwise.
// `grown` marks the one retry with a bigger token budget, so it can't loop.
async function claude(apiKey, model, system, user, schema, maxTokens, grown) {
  const body = JSON.stringify({
    model,
    max_tokens: maxTokens,
    // The system prompt is the same every turn and every user, so we let Anthropic cache it:
    // a cache read costs ~10% of a normal input token. The bot's prompt is ~2k tokens, which is
    // most of each request — caching it roughly halves the cost of a whole conversation.
    system: [{ type: "text", text: system, cache_control: { type: "ephemeral" } }],
    messages: Array.isArray(user) ? user : [{ role: "user", content: user }],
    output_config: { format: { type: "json_schema", schema } },
  });
  let lastErr;
  for (let attempt = 0; attempt < 3; attempt++) {
    let r;
    try {
      r = await fetch("https://api.anthropic.com/v1/messages", {
        method: "POST",
        headers: {
          "x-api-key": apiKey,
          "anthropic-version": "2023-06-01",
          "content-type": "application/json",
        },
        body,
      });
    } catch (e) {
      lastErr = new Error("network: " + (e && e.message ? e.message : e));
      await sleep(400 * (attempt + 1));
      continue;
    }
    const raw = await r.text();
    if (!r.ok) {
      lastErr = new Error("anthropic " + r.status + ": " + raw.slice(0, 200));
      if (r.status === 429 || r.status >= 500) { await sleep(500 * (attempt + 1)); continue; } // transient — retry
      throw lastErr; // 4xx (bad request/auth/model) — don't retry
    }
    let data;
    try { data = JSON.parse(raw); }
    catch { throw new Error("non-JSON reply from Claude: " + raw.slice(0, 200)); }
    if (data.type === "error") throw new Error(data.error && data.error.message || "api error");
    const txt = (data.content || []).filter((b) => b.type === "text").map((b) => b.text).join("");
    // Ran out of room mid-object, so the JSON is cut off and will never parse. Retrying the SAME
    // request just truncates in the same place — the only thing that helps is more room. This is
    // what a long first message in Arabic used to hit: Arabic costs far more tokens per character,
    // and the traveller was told to try again on something that could not succeed.
    if (data.stop_reason === "max_tokens" && !grown) {
      return claude(apiKey, model, system, user, schema, Math.min(maxTokens * 2, 8000), true);
    }
    try { return JSON.parse(txt); }
    catch {
      if (!grown) return claude(apiKey, model, system, user, schema, Math.min(maxTokens * 2, 8000), true);
      throw new Error("Claude did not return valid JSON");
    }
  }
  throw lastErr || new Error("api unavailable");
}
function sleep(ms) { return new Promise((res) => setTimeout(res, ms)); }

// --- Generate a missing city (Sonnet — accuracy matters, and it's cached after) --
const CITY_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: ["valid","city","country","flag","region","blurbEn","blurbAr","blurbEs",
    "summerCond","summerTemp","costBudget","costMid","costLux","curSymbol","curRate",
    "lat","lng","poi","food","hotelsBudget","hotelsMid","hotelsLux"],
  properties: {
    valid: { type: "boolean" },
    city: { type: "string" }, country: { type: "string" }, flag: { type: "string" },
    region: { type: "string", enum: ["eu","asia","me","africa","islands","americas","oceania"] },
    blurbEn: { type: "string" }, blurbAr: { type: "string" }, blurbEs: { type: "string" },
    summerCond: { type: "string", enum: CONDS }, summerTemp: { type: "integer" },
    costBudget: { type: "integer" }, costMid: { type: "integer" }, costLux: { type: "integer" },
    curSymbol: { type: "string" }, curRate: { type: "number" },
    lat: { type: "number" }, lng: { type: "number" },
    poi: { type: "array", items: { type: "object", additionalProperties: false,
      required: ["n","a","t","lat","lng"], properties: {
        n: { type: "string", description: "attraction name in English" },
        a: { type: "string", description: "short area/neighbourhood label in English, e.g. 'Old Town', 'Marina' — NOT a translation of the name, never Arabic" },
        t: { type: "array", items: { type: "string", enum: TAGS } },
        lat: { type: "number" }, lng: { type: "number" } } } },
    food: { type: "array", items: { type: "object", additionalProperties: false,
      required: ["n","a"], properties: {
        n: { type: "string", description: "restaurant name in English" },
        a: { type: "string", description: "short cuisine/area label in English, e.g. 'Seafood · Marina' — never Arabic" } } } },
    hotelsBudget: { type: "array", items: { type: "string" } },
    hotelsMid: { type: "array", items: { type: "string" } },
    hotelsLux: { type: "array", items: { type: "string" } },
  },
};

function generateCity(name, apiKey) {
  const system =
    "You produce accurate travel data for a real city or town for a trip-planning app. " +
    "Use only REAL, well-known points of interest and their true latitude/longitude. " +
    "If the requested place is not a real, travelable destination, return valid=false and leave other fields blank/zero.\n" +
    "Rules: costs are USD per person per day (Budget/Mid/Luxury). curSymbol/curRate are the local " +
    "currency symbol and its rate to 1 USD (e.g. EUR curRate 0.92). summerTemp is the typical August high in Celsius. " +
    "Give 7 POIs (each with 1-2 tags from Culture/Food/Nature/Shopping/Relax and real coordinates) and 5 food spots " +
    "(favor halal-friendly or clearly vegetarian options where they genuinely exist, matching real restaurants). " +
    "Give 4-5 real hotel names per tier. All POI names, food names, hotel names, and their area/label fields must be in ENGLISH " +
    "(the ONLY Arabic/Spanish fields are blurbAr/blurbEs). blurbEn/Ar/Es are one short vivid sentence each (Arabic and Spanish translations). " +
    "flag is the country's flag emoji. Pick region from the allowed list.";
  return claude(apiKey, "claude-sonnet-5", system, "Generate travel data for: " + name, CITY_SCHEMA, 2200);
}

// --- Widen a city's restaurant list (Sonnet — real names matter, and it's cached after) -------
const FOOD_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: ["valid", "food"],
  properties: {
    valid: { type: "boolean" },
    food: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["n", "a"],
        properties: {
          n: { type: "string", description: "the restaurant's real name, in English" },
          a: { type: "string", description: "cuisine and area, in English, e.g. 'Italian · Old Town'" },
        },
      },
    },
  },
};

function generateFood(name, country, apiKey) {
  const system =
    "You list real, currently-open, well-known restaurants in a specific city for a travel app. " +
    "If the place is not a real city, return valid=false and an empty list.\n" +
    "Give 18 places and make them GENUINELY VARIED — a traveller on a long stay should never see the " +
    "same cuisine twice in a row, and someone who does not want the local cuisine should still find " +
    "several options. Cover, as far as the city honestly allows: 2 well-loved local places, one " +
    "Italian/pizza, one grill or steakhouse, one seafood, one clearly vegetarian or vegan-friendly, " +
    "one cafe or breakfast spot, one family-friendly casual place, one budget/street-food favourite, " +
    "and one more international kitchen that genuinely exists there (Indian, Lebanese, Japanese, " +
    "Turkish, whatever fits). Favour halal-friendly places where they genuinely exist. " +
    "Every one must be a place that is genuinely well regarded — the kind that holds a solid rating " +
    "on Google, roughly 4 out of 5 or better, with enough reviews to mean something. A quiet, " +
    "well-loved local place beats a famous one people complain about. " +
    "Never invent a restaurant, and never list a chain that isn't actually in that city. " +
    "`n` is the real name and `a` is 'Cuisine · Neighbourhood' — BOTH in English, never Arabic, " +
    "and keep `a` under 30 characters.";
  return claude(apiKey, "claude-sonnet-5", system, "Restaurants in: " + name + (country ? ", " + country : ""), FOOD_SCHEMA, 2200);
}

// --- Parse a free-text / voice trip description (Haiku — cheap, runs per plan) ---
const PARSE_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: ["cities", "days", "vibes", "budget", "roadtrip"],
  properties: {
    cities: { type: "array", items: { type: "string" } },
    days: { type: "integer" },
    vibes: { type: "array", items: { type: "string", enum: TAGS } },
    budget: { type: "string", enum: ["Budget", "Mid-range", "Luxury"] },
    roadtrip: { type: "boolean" },
  },
};

// --- Conversational trip assistant (Haiku) — chats, then hands off a trip to build --------------
const CHAT_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: ["reply", "ready", "cities", "nights", "extras", "days", "vibes", "budget", "roadtrip", "area", "adults", "kids", "chips"],
  properties: {
    reply: { type: "string" },      // the message to show the user
    ready: { type: "boolean" },     // true once there's enough to build a trip
    cities: { type: "array", items: { type: "string" } }, // best base city per stop, in order (when ready)
    nights: { type: "array", items: { type: "integer" } }, // nights per city, same order/length as cities ([] when unknown)
    extras: {                                             // small stops to add to a day (a cafe, an ice cream place)
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["day", "name"],
        properties: { day: { type: "integer" }, name: { type: "string" } },
      },
    },
    area: { type: "string" },       // where they want to stay in the first city (e.g. "Patong", "city center"); "" if they don't mind
    adults: { type: "integer" },    // how many adults are travelling (0 = not asked yet / unknown)
    kids: { type: "integer" },      // how many children (0 = none)
    days: { type: "integer" },
    vibes: { type: "array", items: { type: "string", enum: TAGS } },
    budget: { type: "string", enum: ["Budget", "Mid-range", "Luxury"] },
    roadtrip: { type: "boolean" },
    chips: { type: "array", items: { type: "string" } }, // 0-4 short tappable quick replies for the user
  },
};

function chatTurn(messages, apiKey) {
  const system =
    "You are Bosla (بوصلة), a warm, concise travel assistant inside a trip-planning app. " +
    "Your job: in a few short friendly turns, learn (a) roughly WHERE they want to go — a place, or " +
    "a vibe you turn into a concrete suggestion — and (b) HOW MANY days. Ask ONE question at a time, keep every " +
    "reply to 1-3 sentences, no lists. Be a real RECOMMENDER: if they're unsure where, or ask for ideas, suggest " +
    "2-3 fitting destinations (keep them geographically sensible and make sure each city is in its CORRECT country) " +
    "and let them pick. Proactively propose a sensible route order and day split when helpful. " +
    "NEVER assume the user's country, nationality, home city, or where they live — do NOT say 'here', 'at home', " +
    "'عندنا', 'near you', or imply you know their location. Only apply passport/visa constraints if the user " +
    "EXPLICITLY states their nationality; otherwise don't mention visas. " +
    "ROAD TRIPS: if the trip involves driving between stops, a full plan needs the CAR LOGISTICS, so ask about them " +
    "(one short question at a time) BEFORE you finish: are they renting a car? Is it a LOOP (drop the car back where " +
    "they picked it up / fly home from the same airport) or ONE-WAY (drop it in a different city and fly out from " +
    "there)? Which city/airport will they fly home from? Then reflect the answer in `cities`: for a loop, make the " +
    "LAST stop the same city they started from (the return-to-airport leg); for one-way, make the last stop the " +
    "city they fly out of. Set roadtrip=true for these. " +
    "THE APP EXPLAINS ARRIVAL BY ITSELF, so do not turn an airport into a stop. Every plan already " +
    "opens by telling the traveller which airport they land at and how to cover the last leg — the " +
    "drive or the light aircraft, with times and costs. So a gateway city belongs in `cities` ONLY " +
    "when they say in so many words that they want to SLEEP there. 'I'll drive to Garmisch directly' " +
    "means cities is ['Garmisch-Partenkirchen'] and Munich appears nowhere, not as one night and not " +
    "as five. Putting it in anyway invents a stay they refused and pushes every later day back. " +
    "ARRIVAL & DEPARTURE — ALWAYS ACCOUNT FOR THIS. Many towns have no airport, so the traveller lands somewhere " +
    "else and continues by car or train. Before finishing, work out which airport they realistically fly into and " +
    "out of, and SAY IT in your reply — e.g. for Garmisch-Partenkirchen: 'You'd fly into Munich, then it's about a " +
    "1.5h drive to Garmisch — do you want a night in Munich first, or drive straight down?'. Reflect the answer in " +
    "`cities`: ONLY put the gateway city in `cities` if they EXPLICITLY agree to spend a night there. If they drive " +
    "straight through, say no, ignore the question, or answer with something else, the gateway city is NOT a stop — " +
    "mention the arrival drive in your reply and leave it out of `cities`. If they say they are driving, live in that " +
    "country, or arrive overland, there is no gateway city at all; drop the airport question entirely. Do the same for " +
    "the flight home — make the departure city the LAST stop only when they say they need a night there. Never " +
    "produce a plan that silently assumes they materialise in a town with no airport. " +
    "NEVER ADD A CITY THEY DID NOT ASK FOR. `cities` may contain only places the traveller named themselves or " +
    "explicitly agreed to. If you suggested somewhere and they replied with a different plan, or just didn't take it " +
    "up, they declined it — leave it out. When they name one place and say how long ('5 nights in El Gouna'), that " +
    "is the WHOLE trip: cities=['El Gouna'], nights=[5]. Your `reply` and your `cities` must describe the SAME trip — " +
    "if you write 'building your El Gouna escape', then cities must be exactly ['El Gouna'] and nothing else. " +
    "WHO'S TRAVELLING: also ask, in ONE short question, how many people are going and whether any children are " +
    "coming (e.g. 'How many of you are travelling — and any kids?'). Put the answer in `adults` and `kids` " +
    "(kids=0 when none). Ask it only ONCE, and if they already said (e.g. 'me and my wife', 'family of 4 with 2 " +
    "kids') just fill the numbers without asking. If they never say, leave adults=0 and kids=0 and don't block the " +
    "trip on it. Offer chips like 'Just me', '2 adults', 'Family with kids'. " +
    "WHERE THEY'LL STAY: after the destination is settled, ask ONE short question about which area they want to " +
    "stay in — e.g. 'Where do you want to be based? Near the beach, city center, near the airport, or somewhere " +
    "specific in mind?' — and offer chips for the areas that actually make sense in THAT city (for Phuket: 'Patong', " +
    "'Kata Beach', 'Old Town'; for Dubai: 'Marina', 'Downtown'). Put their answer in `area` (a real neighbourhood " +
    "name when they name one, otherwise a short phrase like 'city center' / 'near the airport'). Ask it only ONCE; " +
    "if they already said where they want to stay, or they say it doesn't matter / you choose, set area='' and move " +
    "on. Never block the trip on this question. " +
    "Once you have at least one concrete destination (named or agreed) AND a rough number of days — and, for a road " +
    "trip, the car return/airport plan — set ready=true, and fill cities (the best single MAIN city per stop, in " +
    "visit order, common English names), days, vibes (0-3), budget (default Mid-range), roadtrip, area, adults and " +
    "kids. When ready, make your reply a short confirmation like 'Perfect — building your Alps loop from Munich " +
    "now.' Until ready, set ready=false and cities=[]. Set area='' and adults/kids=0 whenever you don't know yet, and " +
    "nights=[] and extras=[] whenever you have nothing to put in them. " +
    "ALWAYS fill `chips` with 2-4 SHORT tappable quick-replies (under ~20 chars each, in the user's language) that " +
    "answer your current question effortlessly — e.g. day counts ('5 days','7 days','10 days'), the destinations you " +
    "just suggested, budgets, or for the car question ('Loop, same airport','One-way','Renting a car'). Leave chips " +
    "empty only when ready=true. NEVER end a turn with a bare acknowledgement. A reply like 'تمام', " +
    "'Okay' or 'Got it' on its own is a dead end — the traveller is left with nothing to tap and no trip. " +
    "Every single reply must do ONE of two things: ask the next question AND offer chips, or set " +
    "ready=true and hand over the trip. If they have just answered your last open question and you have a " +
    "destination and a rough number of days, you already have enough — set ready=true and build it rather " +
    "than acknowledging and stopping. " +
    "WHAT THE APP ITSELF CAN DO — SAY SO WHEN IT'S RELEVANT. Many things people ask you for are already features " +
    "of the finished plan, so never answer 'I can't' and never promise to do it yourself in the chat. Instead say, " +
    "in ONE short sentence, that it's waiting for them on the plan — e.g. 'And once the plan is up you can tap any " +
    "place to see a photo of it.' Mention it when they ask for it, and when you confirm the plan is ready pick the " +
    "ONE feature that best answers what they were after and mention just that (never a list). The plan gives them: " +
    "a photo of any place (hover it on a computer, tap the small photo button on a phone); every place name opens in " +
    "Google Maps, and each city-to-city leg links to the real driving route or a flight search; swap any single " +
    "sight or restaurant for another, or reshuffle a whole day; breakfast, lunch and dinner every day, with a map " +
    "search for more restaurants if they don't want the local picks; set the nights per city freely (8 here, 4 " +
    "there) and delete a city they don't want; change how many adults and kids are travelling; a hotel search they " +
    "steer by area and by type (hotel, apartment, resort, villa, hostel); a budget breakdown with a currency " +
    "converter and a check against their own budget; weather, prayer times and halal notes, useful local phrases, " +
    "handy apps and a packing list; and they can save the trip, share a link, print it as a PDF or add it to their " +
    "calendar, in English, Arabic or Spanish. " +
    "EDITING A TRIP THAT ALREADY EXISTS. The traveller's message may end with a bracketed line like " +
    "'[Current plan - cities: Munich 2n > Garmisch 3n; total days: 5; travellers: 2 adults, 1 kid; staying near: Marina]'. " +
    "They did not type that — it is the trip already on their screen, and it is only a STARTING POINT. " +
    "If anything earlier in this conversation contradicts it, the conversation wins: someone who was looking at a " +
    "Dubai plan and then described eight days in Phuket and Bangkok is REPLACING the trip, not editing it, and " +
    "`cities` must be exactly the places they asked for with Dubai gone. Never hand back the cities in the bracketed " +
    "line when the traveller has named somewhere else, however many turns ago — a short later answer like " +
    "'ما يفرق' or 'you choose' is answering your question about the NEW trip, not abandoning it. " +
    "Otherwise — when they are genuinely adjusting the trip on screen — you are EDITING, never starting " +
    "over: apply ONLY the change they asked for and carry everything else through untouched. Set ready=true and return the " +
    "COMPLETE updated trip — every city in order, days, nights, area, adults, kids — because anything you leave out is lost. " +
    "Use `nights` to give the exact nights per city (same order and length as `cities`) whenever a split is known or asked " +
    "for, e.g. 8 nights in Phuket and 4 in Bangkok; leave it empty when you don't know. If they ask to ADD a small stop — a " +
    "coffee shop, an ice cream place, a viewpoint, a market — put it in `extras` as {day, name} using the day number from " +
    "their plan, name a real place in the right city, and leave cities/days/nights exactly as they were. If they want to " +
    "change one specific sight or restaurant, do NOT rebuild the trip: tell them to tap the small swap arrows next to that " +
    "place on the plan. If they say the trip is good as it is, reply warmly and briefly and set ready=false. " +
    "Stay on travel. Never state hard specifics (exact prices, precise visa rules) as fact — speak generally and " +
    "suggest they verify. Reply in the user's language. " +
    "WRITING QUALITY IS CRITICAL. When the user writes in Arabic, reply ONLY in clean, natural, grammatically-correct " +
    "GULF / KHALEEJI Arabic (Saudi style) — warm and casual (e.g. 'وش رايك', 'تبي', 'خلّينا', 'عندك'), NOT Egyptian and " +
    "NOT stiff formal standard Arabic. Write COMPLETE, COHERENT sentences. Do NOT mix English words, transliterations, " +
    "or internal/technical terms (like 'base', 'loop', 'vibe', 'road trip') into the Arabic text — only real place " +
    "names keep their normal spelling. Never output broken, half-translated, or garbled phrases; before you answer, " +
    "make sure every Arabic sentence reads naturally to a Gulf speaker. Both `reply` and every item in `chips` must " +
    "follow this same clean-Arabic rule. Re-read your Arabic before sending it: correct spelling, correct " +
    "grammar, correct word order, no missing or duplicated words, no dropped letters, and never a sentence " +
    "that stops halfway. A single Arabic mistake is worse than a slower answer.";
  // Arabic is the one language a small model keeps getting wrong (broken grammar, half-translated
  // words). Real users noticed, so Arabic conversations go to the bigger model; EN/ES stay on Haiku.
  // 2400, not 1200: the schema carries the reply, the chips, the cities, the nights and the extras,
  // and Arabic spends roughly twice the tokens per character that English does.
  return claude(apiKey, writesArabic(messages) ? "claude-sonnet-5" : "claude-haiku-4-5", system, messages, CHAT_SCHEMA, 2400);
}

// True when the traveller is actually writing Arabic (not just one stray word).
function writesArabic(messages) {
  const said = (Array.isArray(messages) ? messages : [])
    .filter((m) => m && m.role === "user")
    .map((m) => String(m.content || ""))
    .join(" ");
  const arabic = (said.match(/[\u0600-\u06FF]/g) || []).length;
  const letters = (said.match(/[\u0600-\u06FFA-Za-z]/g) || []).length;
  return letters > 0 && arabic / letters > 0.3;
}

// --- Suggest destinations from a vibe/need when the user names no place (Haiku) ------------------
const SUGGEST_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: ["suggestions", "days", "vibes", "budget", "roadtrip"],
  properties: {
    suggestions: { type: "array", items: { type: "object", additionalProperties: false,
      required: ["place", "country", "flag", "why"], properties: {
        place: { type: "string" }, country: { type: "string" },
        flag: { type: "string" }, why: { type: "string" } } } },
    days: { type: "integer" },
    vibes: { type: "array", items: { type: "string", enum: TAGS } },
    budget: { type: "string", enum: ["Budget", "Mid-range", "Luxury"] },
    roadtrip: { type: "boolean" },
  },
};

function suggestTrip(text, apiKey) {
  const system =
    "The user describes what they want from a trip but usually does NOT name a destination. " +
    "Suggest 2-3 real destinations that genuinely fit. For each: place = the single best CITY to plan " +
    "for that activity (e.g. safari → Nairobi or Arusha; skiing → Chamonix), country = its country, " +
    "flag = the country's flag emoji, why = one short friendly sentence on why it fits. " +
    "Make the suggestions genuinely distinct and relevant, and make sure each city is in its CORRECT country. " +
    "Do NOT assume the user's country or where they live; don't say 'here' or 'near you'. " +
    "Honor every constraint the user gives: if they mention a nationality/passport, only pick countries that are " +
    "visa-free or visa-on-arrival for it (e.g. a Philippine passport: yes Thailand/Indonesia/Malaysia, no Australia/NZ); " +
    "if they want to drive / self-drive / a road trip, set roadtrip true and pick places that suit driving. " +
    "Write `why` in the SAME language the user wrote in; if they wrote in Arabic, use warm Gulf/Khaleeji (Saudi) " +
    "dialect, not Egyptian or formal standard Arabic. " +
    "days: total days if stated, else 0. vibes: 0-3 from the allowed tags. budget: default Mid-range.";
  return claude(apiKey, "claude-haiku-4-5", system, text, SUGGEST_SCHEMA, 700);
}

function parseTrip(text, apiKey) {
  const system =
    "Extract a structured trip from the user's description (any language, typos allowed). " +
    "cities: ONLY destinations the user EXPLICITLY names, in the order visited, corrected to common English names. " +
    "If the user names no specific city or country and only describes a vibe/need, return an EMPTY cities array — " +
    "do NOT invent destinations (a separate step will suggest places to them). " +
    "days: total days — if the text lists nights per stop, SUM them; 0 if not stated. vibes: 0-3 from the allowed tags. " +
    "budget: Budget, Mid-range, or Luxury (default Mid-range). " +
    "roadtrip: true ONLY if the named cities can realistically be driven between (same country or landmass, not across an ocean).";
  return claude(apiKey, "claude-haiku-4-5", system, text, PARSE_SCHEMA, 500);
}

// --- community ---------------------------------------------------------------------------------
// A published trip is the app's own replayable state plus a title and a first name. The feed is a
// single compact KV record so browsing costs one read; the full trip (state, comments, photo ids)
// is fetched only when opened. Photos are small JPEGs the app compresses before sending, stored
// one per key. All of it is bounded — a public write endpoint with no bounds is an invitation.
const PUB = {
  TITLE: 60, NAME: 30, COMMENT: 240, STATE: 40000,     // character caps
  PHOTO: 220000,                                        // ~160KB of JPEG, base64-grown
  PHOTOS_PER_TRIP: 12, COMMENTS_PER_TRIP: 60,
  FEED: 120,                                            // trips the feed remembers
  DAY_PUBLISH: 5, DAY_PHOTOS: 12, DAY_COMMENTS: 30,     // per address per day
  HIDE_AT: 3,                                           // reports before a trip disappears
};

async function pubSha(str) {
  const b = await crypto.subtle.digest("SHA-1", new TextEncoder().encode(str));
  return [...new Uint8Array(b)].map((x) => x.toString(16).padStart(2, "0")).join("").slice(0, 20);
}
function pubClean(s, max) {
  // control chars out, angle brackets out (the app escapes too — belt and braces), length capped
  return String(s || "").replace(/[\u0000-\u001F<>]/g, "").trim().slice(0, max);
}
async function pubDayCap(env, request, what, cap) {
  const ip = request.headers.get("CF-Connecting-IP") || "anon";
  return (await bump(env.CITIES, "pubrl:" + what + ":" + ip + ":" + today(), 172800)) > cap;
}
async function pubIdx(kv) {
  try { return JSON.parse(await kv.get("pubidx")) || []; } catch (e) { return []; }
}
async function pubIdxSave(kv, idx) {
  try { await kv.put("pubidx", JSON.stringify(idx.slice(0, PUB.FEED))); } catch (e) {}
}
// The feed row is rebuilt from the record, so likes/counts on cards can't drift far from truth.
function pubRow(r) {
  return { id: r.id, t: r.t, title: r.title, name: r.name, lang: r.lang,
    cities: r.cities, days: r.days, likes: r.likes || 0,
    nc: (r.comments || []).length, np: (r.photos || []).length, th: r.th || "" };
}
async function pubTouch(kv, r) {
  await kv.put("pub:" + r.id, JSON.stringify(r));
  const idx = await pubIdx(kv);
  const i = idx.findIndex((x) => x.id === r.id);
  if (r.hidden || r.unlisted) { if (i >= 0) idx.splice(i, 1); }
  else if (i >= 0) idx[i] = pubRow(r);
  else idx.unshift(pubRow(r));
  await pubIdxSave(kv, idx);
}

async function community(body, env, request, origin) {
  const kv = env.CITIES;
  const act = body.action;

  if (act === "pub_feed") {
    return reply({ trips: await pubIdx(kv) }, 200, origin);
  }

  if (act === "pub_get") {
    const raw = await kv.get("pub:" + pubClean(body.id, 40));
    if (!raw) return reply({ error: "not found" }, 404, origin);
    const r = JSON.parse(raw);
    if (r.hidden) return reply({ error: "not found" }, 404, origin);
    delete r.k;                                       // the deletion key is the publisher's alone
    return reply({ trip: r }, 200, origin);
  }

  if (act === "pub_add") {
    if (await pubDayCap(env, request, "add", PUB.DAY_PUBLISH))
      return reply({ error: "daily limit reached", retry: 3600 }, 429, origin);
    const title = pubClean(body.title, PUB.TITLE);
    const name = pubClean(body.name, PUB.NAME) || "Traveller";
    let state;
    try { state = JSON.stringify(body.state); } catch (e) { state = ""; }
    if (!title || !state || state.length < 20) return reply({ error: "missing pieces" }, 400, origin);
    if (state.length > PUB.STATE) return reply({ error: "trip too large" }, 400, origin);
    const cities = (Array.isArray(body.cities) ? body.cities : []).slice(0, 8)
      .map((c) => pubClean(c, 40)).filter(Boolean);
    const days = Math.max(1, Math.min(60, body.days | 0)) || 1;
    const lang = ["en", "ar", "es"].indexOf(body.lang) >= 0 ? body.lang : "en";
    // The same person publishing the same trip again is a double-tap or an edit — never a new
    // card. Fingerprint what the feed actually shows (cities, days, name) per address; a repeat
    // hands back the existing trip so the app can update it in place instead of duplicating it.
    const ip0 = request.headers.get("CF-Connecting-IP") || "anon";
    const sig = await pubSha([cities.join("|").toLowerCase(), days, name.toLowerCase()].join("#"));
    const prior = await kv.get("pubsig:" + ip0 + ":" + sig);
    if (prior && await kv.get("pub:" + prior)) return reply({ id: prior, dupe: 1 }, 200, origin);
    const id = (crypto.randomUUID ? crypto.randomUUID() : String(Math.random()).slice(2)).replace(/-/g, "").slice(0, 16);
    // the deletion key: proof-of-publisher without an account. It goes back to the publishing
    // device once, lives in that device's localStorage, and never appears in pub_get or the feed.
    const delkey = (crypto.randomUUID ? crypto.randomUUID() : String(Math.random()).slice(2)).replace(/-/g, "");
    const r = { id, t: Date.now(), title, name, lang, cities, days, k: delkey,
      state: JSON.parse(state), likes: 0, comments: [], photos: [] };
    if (body.vis === "link") r.unlisted = 1;   // reachable by its link, absent from the feed
    await pubTouch(kv, r);
    await kv.put("pubsig:" + ip0 + ":" + sig, id, { expirationTtl: 2592000 });
    return reply({ id, key: delkey }, 200, origin);
  }

  if (act === "pub_update") {
    // The publisher's own edit: replaces title and plan, keeps likes, comments, photos — and
    // keeps the ORIGINAL timestamp, so updating a trip can never be used to bump it up the feed.
    const id = pubClean(body.id, 40);
    const raw = await kv.get("pub:" + id);
    if (!raw) return reply({ error: "not found" }, 404, origin);
    const r = JSON.parse(raw);
    if (!r.k || r.k !== String(body.key || "")) return reply({ error: "not yours" }, 403, origin);
    const title = pubClean(body.title, PUB.TITLE);
    if (title) r.title = title;
    try {
      const st = JSON.stringify(body.state);
      if (st && st.length >= 20 && st.length <= PUB.STATE) r.state = JSON.parse(st);
    } catch (e) {}
    await pubTouch(kv, r);
    return reply({ id, updated: 1 }, 200, origin);
  }

  if (act === "pub_like") {
    const id = pubClean(body.id, 40);
    // one like per address per trip, forever-ish; the client also remembers its own likes
    const ip = request.headers.get("CF-Connecting-IP") || "anon";
    const seen = await kv.get("publike:" + id + ":" + ip);
    const raw = await kv.get("pub:" + id);
    if (!raw) return reply({ error: "not found" }, 404, origin);
    const r = JSON.parse(raw);
    if (!seen) {
      r.likes = (r.likes || 0) + 1;
      await kv.put("publike:" + id + ":" + ip, "1", { expirationTtl: 31536000 });
      await pubTouch(kv, r);
    }
    return reply({ likes: r.likes || 0 }, 200, origin);
  }

  if (act === "pub_comment") {
    if (await pubDayCap(env, request, "cm", PUB.DAY_COMMENTS))
      return reply({ error: "daily limit reached", retry: 3600 }, 429, origin);
    const id = pubClean(body.id, 40);
    const txt = pubClean(body.txt, PUB.COMMENT);
    const name = pubClean(body.name, PUB.NAME) || "Traveller";
    if (!txt) return reply({ error: "empty" }, 400, origin);
    const raw = await kv.get("pub:" + id);
    if (!raw) return reply({ error: "not found" }, 404, origin);
    const r = JSON.parse(raw);
    if ((r.comments || []).length >= PUB.COMMENTS_PER_TRIP)
      return reply({ error: "comments full" }, 400, origin);
    r.comments.push({ n: name, x: txt, t: Date.now() });
    await pubTouch(kv, r);
    return reply({ comments: r.comments }, 200, origin);
  }

  if (act === "pub_photo_add") {
    if (await pubDayCap(env, request, "ph", PUB.DAY_PHOTOS))
      return reply({ error: "daily limit reached", retry: 3600 }, 429, origin);
    const id = pubClean(body.id, 40);
    const name = pubClean(body.name, PUB.NAME) || "Traveller";
    const data = String(body.data || "");
    if (data.indexOf("data:image/jpeg;base64,") !== 0 && data.indexOf("data:image/webp;base64,") !== 0)
      return reply({ error: "jpeg or webp only" }, 400, origin);
    if (data.length > PUB.PHOTO) return reply({ error: "photo too large" }, 400, origin);
    const raw = await kv.get("pub:" + id);
    if (!raw) return reply({ error: "not found" }, 404, origin);
    const r = JSON.parse(raw);
    // the album belongs to the traveller who published the trip — same key that guards deletion
    if (!r.k || r.k !== String(body.key || "")) return reply({ error: "owner only" }, 403, origin);
    if ((r.photos || []).length >= PUB.PHOTOS_PER_TRIP)
      return reply({ error: "photos full" }, 400, origin);
    const pid = id + "." + ((r.photos || []).length + 1) + "." + String(Date.now()).slice(-5);
    const caption = pubClean(body.caption, 140);
    await kv.put("pubphoto:" + pid, JSON.stringify({ n: name, d: data, c: caption }));
    r.photos.push(pid);
    // a matchbox-sized thumb rides along in the feed row so cards can show a real photo without
    // fetching every full image. First photo only, hard-capped tiny.
    const th = String(body.thumb || "");
    if (!r.th && th.indexOf("data:image/jpeg;base64,") === 0 && th.length <= 17000) r.th = th;
    await pubTouch(kv, r);
    return reply({ pid, photos: r.photos }, 200, origin);
  }

  if (act === "pub_photo") {
    const raw = await kv.get("pubphoto:" + pubClean(body.pid, 60));
    if (!raw) return reply({ error: "not found" }, 404, origin);
    return reply(JSON.parse(raw), 200, origin);
  }

  if (act === "pub_photo_del") {
    const id = pubClean(body.id, 40);
    const pid = pubClean(body.pid, 60);
    const raw = await kv.get("pub:" + id);
    if (!raw) return reply({ error: "not found" }, 404, origin);
    const r = JSON.parse(raw);
    if (!r.k || r.k !== String(body.key || "")) return reply({ error: "owner only" }, 403, origin);
    const i = (r.photos || []).indexOf(pid);
    if (i < 0) return reply({ photos: r.photos || [] }, 200, origin);   // already gone
    r.photos.splice(i, 1);
    try { await kv.delete("pubphoto:" + pid); } catch (e) {}
    if (i === 0) delete r.th;   // the card face was this photo's thumb — never show a deleted picture
    await pubTouch(kv, r);
    return reply({ photos: r.photos }, 200, origin);
  }

  if (act === "pub_del") {
    const id = pubClean(body.id, 40);
    const raw = await kv.get("pub:" + id);
    if (!raw) return reply({ ok: 1 }, 200, origin);   // already gone is still gone
    const r = JSON.parse(raw);
    if (!r.k || r.k !== String(body.key || "")) return reply({ error: "not yours" }, 403, origin);
    for (const pid of r.photos || []) { try { await kv.delete("pubphoto:" + pid); } catch (e) {} }
    try { await kv.delete("pub:" + id); } catch (e) {}
    const idx = await pubIdx(kv);
    const i = idx.findIndex((x) => x.id === id);
    if (i >= 0) { idx.splice(i, 1); await pubIdxSave(kv, idx); }
    return reply({ ok: 1 }, 200, origin);
  }

  if (act === "pub_report") {
    const id = pubClean(body.id, 40);
    const ip = request.headers.get("CF-Connecting-IP") || "anon";
    const seen = await kv.get("pubrep:" + id + ":" + ip);
    if (seen) return reply({ ok: 1 }, 200, origin);
    await kv.put("pubrep:" + id + ":" + ip, "1", { expirationTtl: 31536000 });
    const n = await bump(kv, "pubreports:" + id, 31536000);
    if (n >= PUB.HIDE_AT) {
      const raw = await kv.get("pub:" + id);
      if (raw) { const r = JSON.parse(raw); r.hidden = 1; await pubTouch(kv, r); }
    }
    return reply({ ok: 1 }, 200, origin);
  }

  return reply({ error: "unknown action" }, 400, origin);
}


// --- city photographs, legally ------------------------------------------------------------------
// The pipeline: the app names the city -> Wikipedia's lead image for that exact page is the
// closest thing the internet has to "the one iconic photo" -> Commons tells us its author and
// licence -> only openly-licensed images pass -> the record (url, author, licence, source page)
// is cached in KV forever and the app displays it WITH the attribution. No scraping, no
// hotlinking mystery images, nothing whose provenance we cannot show. Wikimedia asks callers to
// identify themselves, so we do.
const PHOTO_UA = { headers: { "User-Agent": "Bosla-Travel-App/1.0 (https://aalfadhala10.github.io/travel-itinerary-skill/)" } };
const LICENCE_OK = /^(public domain|pd|cc0|cc[ -]by(?:[ -]sa)?(?: \d\.\d)?)$/i;

// The photo should be the postcard, not the street: Doha is its corniche towers, Cairo is the
// pyramids, Dubai is the Burj. For the cities everyone flies to, the landmark is curated below —
// each value is the English Wikipedia article whose lead image IS that postcard. For any other
// city a traveller types, Claude names the landmark once (cheap model, cached in KV forever),
// and the city page itself remains the fallback when neither yields a usable, openly-licensed
// image.
const ICON = {
  doha: "West Bay (Doha)", cairo: "Giza pyramid complex", dubai: "Burj Khalifa",
  abudhabi: "Sheikh Zayed Grand Mosque", riyadh: "Kingdom Centre", kuwaitcity: "Kuwait Towers",
  manama: "Bahrain World Trade Center", muscat: "Sultan Qaboos Grand Mosque",
  mecca: "Masjid al-Haram", medina: "Al-Masjid an-Nabawi", amman: "Amman Citadel",
  petra: "Al-Khazneh", luxor: "Karnak", istanbul: "Hagia Sophia", paris: "Eiffel Tower",
  rome: "Colosseum", london: "Big Ben", newyork: "Statue of Liberty",
  sanfrancisco: "Golden Gate Bridge", sydney: "Sydney Opera House", agra: "Taj Mahal",
  delhi: "India Gate", moscow: "Saint Basil's Cathedral", beijing: "Forbidden City",
  athens: "Acropolis of Athens", barcelona: "Sagrada Família", singapore: "Marina Bay Sands",
  kualalumpur: "Petronas Towers", bangkok: "Wat Arun", tokyo: "Tokyo Tower",
  kyoto: "Kinkaku-ji", seoul: "Gyeongbokgung", shanghai: "The Bund", toronto: "CN Tower",
  lasvegas: "Las Vegas Strip", la: "Hollywood Sign", chicago: "Cloud Gate",
  washington: "United States Capitol", rio: "Christ the Redeemer",
  cusco: "Machu Picchu", cancun: "Chichen Itza", casablanca: "Hassan II Mosque",
  marrakech: "Jemaa el-Fnaa", venice: "Grand Canal (Venice)", florence: "Florence Cathedral",
  pisa: "Leaning Tower of Pisa", milan: "Milan Cathedral", munich: "Marienplatz",
  berlin: "Brandenburg Gate", vienna: "Schönbrunn Palace", prague: "Charles Bridge",
  budapest: "Hungarian Parliament Building", capetown: "Table Mountain",
  seville: "Plaza de España, Seville", amsterdam: "Canals of Amsterdam",
  sanaa: "Old City of Sana'a", giza: "Giza pyramid complex", hongkong: "Victoria Harbour",
};

const ICON_SCHEMA = {
  type: "object", additionalProperties: false, required: ["title"],
  properties: { title: { type: "string", description: "English Wikipedia article title of the single most iconic landmark of the city, or empty string if unsure" } },
};

async function cityPhoto(body, env, origin) {
  const kv = env.CITIES;
  const name = String(body.name || "").slice(0, 60).trim();
  const country = String(body.country || "").slice(0, 60).trim();
  if (name.length < 2) return reply({ error: "name too short" }, 400, origin);
  const ckey = "photo:v2:" + cityKey(name);
  if (kv) {
    const hit = await kv.get(ckey);
    if (hit) return reply(JSON.parse(hit), 200, origin);
  }

  // which article carries the postcard for this city?
  let iconTitle = ICON[cityKey(name)] || null;
  if (!iconTitle && env.ANTHROPIC_API_KEY && !(await overBudget(env, "llm", DAY_LLM_CAP))) {
    try {
      const got = await claude(env.ANTHROPIC_API_KEY, "claude-haiku-4-5",
        "Name the single most iconic, photogenic landmark of the given city — the one a postcard would show. " +
        "Reply with the exact English Wikipedia article title for it. If you are not confident, reply with an empty title.",
        name + (country ? ", " + country : ""), ICON_SCHEMA, 100);
      const t = got && String(got.title || "").trim();
      if (t && t.length > 2 && t.length < 80) iconTitle = t;
      await spend(env, "llm");
    } catch (e) { iconTitle = null; }
  }

  async function leadImage(title) {
    const u = "https://en.wikipedia.org/w/api.php?action=query&format=json&origin=*&redirects=1&prop=pageimages&piprop=name&titles=" + encodeURIComponent(title);
    const r = await fetch(u, PHOTO_UA); if (!r.ok) return null;
    const d = await r.json();
    const p = Object.values((d.query && d.query.pages) || {})[0];
    return (p && p.pageimage) ? p.pageimage : null;
  }
  async function fileInfo(file) {
    const u = "https://commons.wikimedia.org/w/api.php?action=query&format=json&origin=*&prop=imageinfo&iiprop=url|extmetadata&iiurlwidth=900&titles=" + encodeURIComponent("File:" + file);
    const r = await fetch(u, PHOTO_UA); if (!r.ok) return null;
    const d = await r.json();
    const p = Object.values((d.query && d.query.pages) || {})[0];
    const ii = p && p.imageinfo && p.imageinfo[0];
    if (!ii || !ii.thumburl) return null;
    const md = ii.extmetadata || {};
    const lic = md.LicenseShortName && md.LicenseShortName.value || "";
    if (!LICENCE_OK.test(lic.trim())) return null;             // free licences only, or no photo at all
    const author = String(md.Artist && md.Artist.value || "").replace(/<[^>]*>/g, "").trim().slice(0, 80);
    return { url: ii.thumburl, author: author || "Wikimedia Commons", licence: lic.trim(), src: ii.descriptionurl || "" };
  }

  let photo = null;
  try {
    // the landmark's postcard first; the city page only when the landmark yields nothing usable
    if (iconTitle) {
      const f0 = await leadImage(iconTitle);
      if (f0) photo = await fileInfo(f0);
    }
    if (!photo) {
      const file = (country ? await leadImage(name + ", " + country) : null) || await leadImage(name);
      if (file) photo = await fileInfo(file);
    }
  } catch (e) { photo = null; }

  const rec = { photo };
  if (kv) {
    // a found photo is cached forever (the licence record travels with it); a miss is retried
    // after a week, because pages gain photos
    try { await kv.put(ckey, JSON.stringify(rec), photo ? undefined : { expirationTtl: 604800 }); } catch (e) {}
  }
  return reply(rec, 200, origin);
}


// --- indicative hotel prices --------------------------------------------------------------------
// Real numbers only ever come from a real source. Hotellook (Travelpayouts) serves cached market
// prices and pays an affiliate commission on bookings — the owner adds TP_TOKEN (and TP_MARKER
// for the commission) as Cloudflare secrets, and until then this action says so instead of
// guessing. Prices are cached six hours per hotel+dates and always labelled approximate.
async function hotelPrice(body, env, origin) {
  if (!env.TP_TOKEN) return reply({ needsKey: 1 }, 200, origin);
  const kv = env.CITIES;
  const name = String(body.name || "").slice(0, 80).trim();
  const city = String(body.city || "").slice(0, 60).trim();
  const ci = String(body.checkin || ""), co = String(body.checkout || "");
  const ad = Math.max(1, Math.min(8, body.adults | 0)) || 2;
  if (!name || !city) return reply({ error: "missing" }, 400, origin);
  if (!/^\d{4}-\d{2}-\d{2}$/.test(ci) || !/^\d{4}-\d{2}-\d{2}$/.test(co))
    return reply({ prices: null, noDates: 1 }, 200, origin);

  const ckey = "hp:" + cityKey(city) + ":" + cityKey(name).slice(0, 24) + ":" + ci + ":" + co + ":" + ad;
  if (kv) { const hit = await kv.get(ckey); if (hit) return reply(JSON.parse(hit), 200, origin); }

  let out = { prices: null };
  try {
    const lu = await fetch("https://engine.hotellook.com/api/v2/lookup.json?query=" +
      encodeURIComponent(name + " " + city) + "&lang=en&lookFor=hotel&limit=3&token=" + env.TP_TOKEN);
    const ld = lu.ok ? await lu.json() : null;
    const hotel = ld && ld.results && ld.results.hotels && ld.results.hotels[0];
    if (hotel && hotel.id) {
      const pr = await fetch("https://engine.hotellook.com/api/v2/cache.json?locationId=" + hotel.locationId +
        "&checkIn=" + ci + "&checkOut=" + co + "&adults=" + ad + "&currency=usd&limit=200&token=" + env.TP_TOKEN);
      const pd = pr.ok ? await pr.json() : null;
      const row = Array.isArray(pd) ? pd.find((x) => x.hotelId === hotel.id) : null;
      if (row && row.priceFrom > 0) {
        const marker = env.TP_MARKER ? "&marker=" + encodeURIComponent(env.TP_MARKER) : "";
        out = { prices: { from: Math.round(row.priceFrom), avg: Math.round(row.priceAvg || 0) || null,
          currency: "USD", stay: true, hotel: hotel.label || name,
          book: "https://search.hotellook.com/hotels?hotelId=" + hotel.id + "&checkIn=" + ci +
            "&checkOut=" + co + "&adults=" + ad + marker } };
      }
    }
  } catch (e) { out = { prices: null }; }
  if (kv) { try { await kv.put(ckey, JSON.stringify(out), { expirationTtl: 21600 }); } catch (e) {} }
  return reply(out, 200, origin);
}
